# =================================================================
# LOGIK FÖR SKAFFERIBELYSNING
# =================================================================
# All logik för att styra belysningen i skafferiet.
# -----------------------------------------------------------------

# --- Sensor som styr automationen ---
template:
  - binary_sensor:
      - name: kok_skafferi_presence_light_automation_control
        unique_id: kok_skafferi_presence_light_automation_control
        state: >
          {{ is_state('binary_sensor.kok_presence', 'on') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Kök skafferibelysning
    id: kok_skafferibelysning
    triggers:
      - trigger: state
        entity_id: binary_sensor.kok_skafferi_presence_light_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.kok_skafferi_presence_light_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.kok_skafferi