# =================================================================
# LOGIK FÖR TAKBELYSNING
# =================================================================
# All logik för att styra den primära takbelysningen i köket.
# -----------------------------------------------------------------

# --- Profil för adaptiv belysning ---
adaptive_lighting:
  - name: Kök
    lights:
      - light.kok_bankbelysning
      - light.kok_koksbord_1
      - light.kok_koksbord_2
      - light.kok_kokso
      - light.kok_tak
      - light.kok_skafferi
      - light.kok_vedspis
    prefer_rgb_color: false
    transition: 30
    initial_transition: 3
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
    adapt_only_on_bare_turn_on: true

# --- Inställning för ljusnivå ---
input_number:
  kok_light_level:
    name: Ljusstyrka kök för belysning
    min: 0
    max: 200
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on

# --- Sensorer som styr automationen ---
template:
  - binary_sensor:
      # Steg 1: Är det för ljust inne för att tända taklamporna?
      - name: kok_lightlevel
        unique_id: kok_lightlevel
        device_class: light
        delay_on:
          minutes: 10
        state: >
          {{ states('sensor.kok_hue_motion_sensor_light_level') | float(0) > states('input_number.kok_light_level') | float(0) }}
      
      # Steg 2: Kontrollsensor som triggar automationen.
      - name: kok_presence_light_automation_control
        unique_id: kok_presence_light_automation_control
        state: >
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on')
            or is_state('binary_sensor.hall_presence', 'on') )
            and is_state('binary_sensor.kok_lightlevel', 'off') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Kök takbelysning
    id: kok_takbelysning
    triggers:
      - trigger: state
        entity_id: binary_sensor.kok_presence_light_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.kok_presence_light_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.kok_tak
            - light.kok_koksbord_1
            - light.kok_koksbord_2
            - light.kok_kokso
            - light.hall_byra
            - light.kok_vedspis