# =================================================================
# LOGIK FÖR FÖNSTERBELYSNING – KÖK
# =================================================================
# Styr fönsterlamporna i köket via två grupper:
#  - Grundstyrning: tänd/släck vid mörker
#  - Filmläge: tänd/släck vid mörker, men släck vid film
#
# OBS! Styrparametrar hanteras via UI (Helpers):
#  - input_number.fonsterbelysning_light_level
#
# OBS! Lampor styrs via Light Groups i UI:
#  - light.kok_styrning_fonster
#  - light.kok_styrning_fonster_film
# -----------------------------------------------------------------


# =================================================================
# ADAPTIVE LIGHTING-PROFIL
# =================================================================
adaptive_lighting:
  - name: Kök fönster
    lights:
      - light.kok_fonster_1
      - light.kok_fonster_2
      - light.kok_fonster_3
    prefer_rgb_color: false
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 35
    sleep_brightness: 1
    take_over_control: true
    detect_non_ha_changes: false
    adapt_only_on_bare_turn_on: true


# =================================================================
# SENSORER SOM STYR AUTOMATIONEN
# =================================================================
template:
  - binary_sensor:
      # -------------------------------------------------------------
      # Steg 1: Är det mörkt nog ute för fönsterbelysning?
      # -------------------------------------------------------------
      - name: kok_fonster_lightlevel
        unique_id: kok_fonster_lightlevel
        device_class: light
        delay_off:
          minutes: 10
        state: >
          {{ (states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(9999))
              < (states('input_number.fonsterbelysning_light_level') | float(0)) }}

      # -------------------------------------------------------------
      # Steg 2: Grundstyrning (endast mörker)
      # -------------------------------------------------------------
      - name: kok_fonster_automation_control
        unique_id: kok_fonster_automation_control
        state: >
          {{ is_state('binary_sensor.kok_fonster_lightlevel', 'on') }}

      # -------------------------------------------------------------
      # Steg 2: Filmläge (mörker, men släck vid film)
      # -------------------------------------------------------------
      - name: kok_fonster_automation_control_film
        unique_id: kok_fonster_automation_control_film
        state: >
          {{ is_state('binary_sensor.kok_fonster_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off') }}


# =================================================================
# AUTOMATION
# =================================================================
automation:
  - alias: Kök fönsterbelysning
    id: kok_fonsterbelysning
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.kok_fonster_automation_control
          - binary_sensor.kok_fonster_automation_control_film
      - trigger: homeassistant
        event: start

    actions:
      # -------------------------------------------------------------
      # DEL A: Grundstyrning (mörker)
      # -------------------------------------------------------------
      - action: "light.turn_{{ states('binary_sensor.kok_fonster_automation_control') }}"
        target:
          entity_id: light.kok_styrning_fonster

      # -------------------------------------------------------------
      # DEL B: Filmläge (mörker, men släck vid film)
      # -------------------------------------------------------------
      - action: "light.turn_{{ states('binary_sensor.kok_fonster_automation_control_film') }}"
        target:
          entity_id: light.kok_styrning_fonster_film