# =================================================================
# LOGIK FÖR FÖNSTERBELYSNING
# =================================================================
# All logik för att styra fönsterlamporna i köket.
# -----------------------------------------------------------------

# --- Profil för adaptiv belysning ---
adaptive_lighting:
  - name: Kök fönster
    lights:
      - light.kok_fonster_1
      - light.kok_fonster_2
      - light.kok_fonster_3
    prefer_rgb_color: false
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 35
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
    take_over_control: true
    detect_non_ha_changes: false

# --- Sensorer som styr automationerna ---
template:
  - binary_sensor:
      # Steg 1: Är det mörkt nog ute för fönsterbelysning?
      - name: kok_belysning_filament_lightlevel
        unique_id: kok_belysning_filament_lightlevel
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0) < states('input_number.fonsterbelysning_light_level') | float(0) }}
      
      # Steg 2: Kontrollsensor för de stora fönstren.
      - name: kok_belysning_filament_automation_control
        unique_id: kok_belysning_filament_automation_control
        state: >
          {{ is_state('binary_sensor.kok_belysning_filament_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off') }}
      
      # Steg 2: Kontrollsensor för det lilla fönstret.
      - name: kok_belysning_litet_fonster_automation_control
        unique_id: kok_belysning_litet_fonster_automation_control
        state: >
          {{ is_state('binary_sensor.kok_belysning_filament_lightlevel', 'on') }}

# --- Automationer ---
automation:
  - alias: Kök belysning stora fönster
    id: kok_belysning_stora_fonster
    triggers:
      - trigger: state
        entity_id: binary_sensor.kok_belysning_filament_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.kok_belysning_filament_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.kok_fonster_1
            - light.kok_fonster_2
  - alias: Kök belysning litet fönster
    id: kok_belysning_litet_fonster
    triggers:
      - trigger: state
        entity_id: binary_sensor.kok_belysning_litet_fonster_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.kok_belysning_litet_fonster_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.kok_fonster_3