# =================================================================
# KONFIGURATION FÖR TVÄTTMASKIN
# =================================================================
# All logik för att spåra tvättmaskinens förbrukning och status,
# samt skicka notiser när den är klar.
# -----------------------------------------------------------------

# =================================================================
# UTILITY METERS
# =================================================================
# Dessa entiteter spårar tvättmaskinens elförbrukning över olika
# tidsperioder (dag, månad, år).
# -----------------------------------------------------------------
utility_meter:
  tvattmaskin_dag:
    unique_id: tvattmaskin_dag
    source: sensor.tvattmaskin_consumption
    periodically_resetting: false
    cycle: daily
  tvattmaskin_manad:
    unique_id: tvattmaskin_manad # Korrigerat från vattmaskin_manad
    source: sensor.tvattmaskin_consumption
    periodically_resetting: false
    cycle: monthly
#  tvattmaskin_ar:
#    source: sensor.tvattmaskin_consumption
#    cycle: yearly

# =================================================================
# TEMPLATE-SENSORER
# =================================================================
# Denna sensor utgör grunden för automationen.
# -----------------------------------------------------------------
template:
  - binary_sensor:
      # En sensor som blir 'on' när tvättmaskinen drar mer än 5W.
      # Detta indikerar att ett program är igång.
      - name: tvattmaskin
        unique_id: tvattmaskin
        delay_on:
          seconds: 10
        delay_off:
          minutes: 2
        state: "{{ states('sensor.tvattmaskin_effekt') | float(0.0) > 5 }}"

# =================================================================
# AUTOMATIONER
# =================================================================
# Skickar en notis när tvättmaskinen är klar.
# -----------------------------------------------------------------
automation:
  - alias: Tvättmaskin klar
    id: tvattmaskin_klar
    triggers:
      # Triggar när tvättmaskin-sensorn går från 'on' (körs) till 'off' (klar).
      - trigger: state
        entity_id: binary_sensor.tvattmaskin
        from: "on"
        to: "off"
    actions:
      # Skickar en persistent notis i Home Assistant.
      - action: notify.persistent_notification
        data:
          message: "Tvättmaskin"
          title: "Tvätten är klar"
      # Skickar en notis till Mikaels iPhone.
      - action: notify.mobile_app_mikael_iphone
        data:
          message: "Tvättmaskin klar"
          title: "Tvätten är klar"
      # Skickar en notis till Linas iPhone.
      - action: notify.mobile_app_lina_iphone
        data:
          message: "Tvättmaskin klar"
          title: "Tvätten är klar"