# =================================================================
# LOGIK FÖR FÖNSTERBELYSNING
# =================================================================
# All logik för att styra den allmänna fönsterbelysningen.
# -----------------------------------------------------------------

# --- Sensorer som styr automationen ---
template:
  - binary_sensor:
      # Steg 1: Är det mörkt nog ute för fönsterbelysning?
      - name: vardagsrum_belysning_fonster_lightlevel
        unique_id: vardagsrum_belysning_fonster_lightlevel
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0) < states('input_number.fonsterbelysning_light_level') | float(0) }}
      
      # Steg 2: Kontrollsensor som triggar automationen.
      - name: vardagsrum_belysning_fonster_automation_control
        unique_id: vardagsrum_belysning_fonster_automation_control
        state: >
          {{ is_state('binary_sensor.vardagsrum_belysning_fonster_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Vardagsrum belysning fönster
    id: Vardagsrum belysning fönster
    triggers:
      - trigger: state
        entity_id: binary_sensor.vardagsrum_belysning_fonster_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.vardagsrum_belysning_fonster_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.vardagsrum_fonster_piano
            - light.vardagsrum_fonster_trappa
            - light.vardagsrum_fonster_ytterdorr
            - light.vardagsrum_fonster_vitrinskap
            - light.trappa