# =================================================================
# LOGIK FÖR FILAMENTBELYSNING
# =================================================================
# All logik för att styra de dekorativa filamentlamporna.
# -----------------------------------------------------------------

# --- Profil för adaptiv belysning ---
adaptive_lighting:
  - name: Vardagsrum belysning filament
    lights:
      - light.vardagsrum_fonster_hangande
      - light.vardagsrum_fonster_fotogen
      - light.vardagsrum_fonster_piano
      - light.vardagsrum_fonster_trappa
      - light.vardagsrum_fonster_ytterdorr
      - light.vardagsrum_fonster_vitrinskap
    prefer_rgb_color: false
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 35
    sleep_brightness: 1
    take_over_control: true
    detect_non_ha_changes: true

# --- Inställning för ljusnivå ---
input_number:
  vardagsrum_filament_light_level:
    name: Ljusstyrka vardagsrum för belysning filament
    min: 0
    max: 2000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on

# --- Sensorer som styr automationen ---
template:
  - binary_sensor:
      # Steg 1: Är det mörkt nog ute för filamentbelysning?
      - name: vardagsrum_belysning_filament_lightlevel
        unique_id: vardagsrum_belysning_filament_lightlevel
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0) < states('input_number.vardagsrum_filament_light_level') | float(0) }}
      
      # Steg 2: Kontrollsensor som triggar automationen.
      - name: vardagsrum_belysning_filament_automation_control
        unique_id: vardagsrum_belysning_filament_automation_control
        state: >
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on') )
            and is_state('binary_sensor.vardagsrum_belysning_filament_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Vardagsrum belysning filament
    id: Vardagsrum belysning filament
    triggers:
      - trigger: state
        entity_id: binary_sensor.vardagsrum_belysning_filament_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.vardagsrum_belysning_filament_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.vardagsrum_fonster_fotogen
            - light.vardagsrum_fonster_hangande