# =================================================================
# LOGIK FÖR TAKBELYSNING
# =================================================================
# All logik för att styra taklamporna (spottar och lampan över bordet).
# -----------------------------------------------------------------

# --- Profil för adaptiv belysning ---
adaptive_lighting:
  - name: Vardagsrum tak
    lights:
      - light.vardagsrum_tak
      - light.vardagsrum_bord
    prefer_rgb_color: false
    transition: 30
    initial_transition: 2
    interval: 90
    min_brightness: 30
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
    adapt_only_on_bare_turn_on: true

# --- Inställning för ljusnivå ---
input_number:
  vardagsrum_light_level:
    name: Ljusstyrka vardagsrum för belysning
    min: 0
    max: 100
    step: 1
    unit_of_measurement: lx
    icon: mdi:lightbulb-on

# --- Sensorer som styr automationen ---
template:
  - binary_sensor:
      # Steg 1: Är det för ljust inne för att tända taklamporna?
      - name: vardagsrum_lightlevel
        unique_id: vardagsrum_lightlevel
        device_class: light
        delay_on:
          minutes: 10
        state: >
          {{ states('sensor.vardagsrum_hue_motion_sensor_light_level') | float(0) > states('input_number.vardagsrum_light_level') | float(0) }}
      
      # Steg 2: Kontrollsensor som triggar automationen.
      - name: vardagsrum_presence_light_automation_control
        unique_id: vardagsrum_presence_light_automation_control
        state: >
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on')
            or is_state('binary_sensor.hall_presence', 'on') )
            and is_state('binary_sensor.vardagsrum_lightlevel', 'off') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Vardagsrum belysning tak
    id: Vardagsrum belysning tak
    triggers:
      - trigger: state
        entity_id: binary_sensor.vardagsrum_presence_light_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ iif(states('binary_sensor.vardagsrum_presence_light_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.vardagsrum_tak
            - light.vardagsrum_bord