# =================================================================
# LOGIK FÖR VÄRMEGOLV
# =================================================================
# All logik för att styra värmegolvet i barnrummet.
# -----------------------------------------------------------------

# --- Termostat för värmegolvet ---
climate:
  - platform: generic_thermostat
    name: Barnrum värmegolv
    unique_id: Barnrum värmegolv
    cold_tolerance: 0.0
    hot_tolerance: 0.2
    precision: 0.1
    heater: switch.barnrum_varmegolv
    target_sensor: sensor.barnrum_temperature
    min_temp: 7

# --- Automationen som styr termostaten ---
automation:
  - alias: Barnrum värme
    id: barnrum_varme
    triggers:
      - trigger: time_pattern
        minutes: "/30"
    actions:
      - action: climate.set_hvac_mode
        target:
          entity_id: climate.barnrum_varmegolv
        data:
          hvac_mode: "{{ iif(states('binary_sensor.varmegolv_block') == 'on', 'off', 'heat') }}"