# =================================================================
# STYRNING FÖR SOLCELLSBATTERI
# =================================================================
# Denna fil innehåller alla skript och automationer som aktivt
# styr batteriets beteende.
# -----------------------------------------------------------------

# =================================================================
# SKRIPT
# =================================================================
# Dessa skript är återanvändbara "funktioner" som kan anropas från
# automationer för att ställa in batteriet i olika lägen.
# -----------------------------------------------------------------
script:
  ### Skript för att styra batteri ####
  solar_battery_mode:
    sequence:
      - service: modbus.write_register
        data:
          slave: 1
          # MinRsvPct
          address: 40350
          value: "{{ MinRsvPct }}"
          hub: gen24
      - service: modbus.write_register
        data:
          slave: 1
          # InWRte
          address: 40356
          value: "{{ InWRte }}"
          hub: gen24
      - service: modbus.write_register
        data:
          slave: 1
          # OutWRte
          address: 40355
          value: "{{ OutWRte }}"
          hub: gen24
      - service: modbus.write_register
        data:
          slave: 1
          # StorCTLMod
          address: 40348
          value: "{{ StorCTLMod }}"
          hub: gen24

  solar_battery_charge:
    sequence:
      - action: script.solar_battery_mode
        # Charge from solar
        data:
          # Only permit energy storage charging
          StorCTLMod: 2
          MinRsvPct: 1000
          # Set discharge limit of WchaMax to 0%
          OutWRte: 0
          #
          InWRte: 10000

  solar_battery_charge_fixed:
    sequence:
      - action: script.solar_battery_mode
        # Charge fixed
        data:
          StorCTLMod: 3
          MinRsvPct: 1000
          OutWRte: "{{ 65536 - (states('input_number.solar_battery_charge') | int(0) / 10240 * 10000) | int(0) }}"
          #
          InWRte: "{{ (states('input_number.solar_battery_charge') | int(0) / 10240 * 10000) | int(0) }}"

  solar_battery_discharge:
    sequence:
      - action: script.solar_battery_mode
        # Discharge
        data:
          # Only permit energy storage discharging
          StorCTLMod: 1
          MinRsvPct: 1000
          #
          OutWRte: 10000
          # Set charge limit of WchaMax to 0%
          InWRte: 0

  solar_battery_block:
    sequence:
      - action: script.solar_battery_mode
        # Do not permit charging or discharging
        data:
          # Activate both limit values
          StorCTLMod: 3
          MinRsvPct: 1000
          OutWRte: 0
          InWRte: 0

# =================================================================
# AUTOMATION
# =================================================================
# Huvudautomationen som läser av 'solar_battery_mode'-sensorn och
# anropar rätt skript för att ställa in batteriet.
# -----------------------------------------------------------------
automation:
  - alias: solar_battery_mode
    id: solar_battery_mode
    triggers:
      - trigger: state
        entity_id: sensor.solar_battery_mode
      - trigger: state
        entity_id: sensor.p_batt_forecast
    actions:
      - delay:
          seconds: 30
      - choose:
          #
          ### Charge##
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "charge"
            sequence:
              - action: script.solar_battery_mode
                # Charge, InWRte positiv
                data:
                  StorCTLMod: 3
                  MinRsvPct: 1000
                  OutWRte: "{{ 65536 - (0 - states('sensor.p_batt_forecast') | int(0) / 10240 * 10000) | int(0) }}"
                  InWRte: "{{ (0 - states('sensor.p_batt_forecast') | int(0) / 10240 * 10000) | int(0) }}"
          #
          ### Charge##
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "charge_max"
            sequence:
              - action: script.solar_battery_mode
                # Charge, InWRte positiv
                data:
                  StorCTLMod: 3
                  MinRsvPct: 1000
                  OutWRte: "{{ 65536 - (0 - -5000 | int(0) / 10240 * 10000) | int(0) }}"
                  InWRte: "{{ (0 - -5000 | int(0) / 10240 * 10000) | int(0) }}"
          #
          ### Charge from solar ##
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "charge_from_solar"
            sequence:
              - action: script.solar_battery_mode
                # Charge from solar
                data:
                  # Only permit energy storage charging
                  StorCTLMod: 2
                  MinRsvPct: 1000
                  # Set discharge limit of WchaMax to 0%
                  OutWRte: 0
                  #
                  InWRte: 10000
          #
          ### Discharge ###
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "discharge"
            sequence:
              - action: script.solar_battery_mode
                # Discharge
                data:
                  # Only permit energy storage discharging
                  StorCTLMod: 1
                  MinRsvPct: 1000
                  #
                  OutWRte: 10000
                  # Set charge limit of WchaMax to 0%
                  InWRte: 0
          #
          ### Discharge fixed ###
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "discharge_fixed"
            sequence:
              - action: script.solar_battery_mode
                # Discharge fixed
                data:
                  #
                  StorCTLMod: 3
                  #
                  MinRsvPct: 1000
                  #
                  OutWRte: "{{ (states('sensor.p_batt_forecast') | int(0) / 10240 * 10000) | int(0) }}"
                  #
                  InWRte: "{{ 65536 - (states('sensor.p_batt_forecast') | int(0) / 10240 * 10000) | int(0) }}"
          #
          ### Discharge min limit ###
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "discharge_min_limit"
            sequence:
              - action: script.solar_battery_mode
                # Discharge min limit
                data:
                  #
                  StorCTLMod: 1
                  #
                  MinRsvPct: 1000
                  #
                  OutWRte: 10000
                  #
                  InWRte: "{{ 65536 - (states('sensor.p_batt_forecast') | int(0) / 10240 * 10000) | int(0) }}"
          #
    
          ### Block ###
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "blocked"
            sequence:
              - action: script.solar_battery_mode
                # Do not permit charging or discharging
                data:
                  # Activate both limit values
                  StorCTLMod: 3
                  MinRsvPct: 1000
                  OutWRte: 0
                  InWRte: 0
#
          ### Idle ###
          - conditions:
              - condition: state
                entity_id: sensor.solar_battery_mode
                state: "idle"
            sequence:
              - action: script.solar_battery_mode
                # Do not permit charging or discharging
                data:
                  # Activate both limit values
                  StorCTLMod: 3
                  MinRsvPct: 1000
                  OutWRte: 0
                  InWRte: 0