# = ================================================================
# LOGIK FÖR FYSISKA KNAPPAR
# =================================================================
# All logik för att hantera tryck på fysiska knappar i allrummet.
# -----------------------------------------------------------------

# --- Automationer för knappar ---
automation:
  # Styr media och filmläge med knappen vid TV:n.
  - alias: Allrum knapp vid tv
    id: allrum_knapp_vid_tv
    triggers:
      # Trigger för enkeltryck.
      - platform: device
        domain: mqtt
        device_id: 399f935166a8dc9987ba52ae975e5b2c
        type: action
        subtype: single
        id: single_press
      # Trigger för dubbeltryck.
      - platform: device
        domain: mqtt
        device_id: 399f935166a8dc9987ba52ae975e5b2c
        type: action
        subtype: double
        id: double_press
      # Trigger för långtryck.
      - platform: device
        domain: mqtt
        device_id: 399f935166a8dc9987ba52ae975e5b2c
        type: action
        subtype: hold
        id: hold_press
    actions:
      - choose:
          # --- SEKVENS FÖR DUBBELTRYCK ---
          # Startar filmläget.
          - conditions:
              - condition: trigger
                id: double_press
              - condition: state
                entity_id: input_boolean.film
                state: "off"
            sequence:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.film
          
          # --- SEKVENS FÖR ENKELTRYCK ---
          # Spelar/pausar media.
          - conditions:
              - condition: trigger
                id: single_press
            sequence:
              - action: "media_player.media_{{ 'pause' if is_state('media_player.allrum', 'playing') else 'play' }}"
                target:
                  entity_id: media_player.allrum
          
          # --- SEKVENS FÖR LÅNGTRYCK ---
          # Växlar "film spelar"-läget.
          - conditions:
              - condition: trigger
                id: hold_press
            sequence:
              - action: input_boolean.toggle
                target:
                  entity_id: input_boolean.film_spelar