# =================================================================
# LOGIK FÖR FILMLÄGE
# =================================================================
# All logik för att automatiskt hantera filmläget baserat på
# medieuppspelning i allrummet.
# -----------------------------------------------------------------

# --- Hjälpare för att styra filmläget ---
# Dessa booleans används för att hålla koll på de olika stegen i filmläget.
input_boolean:
  # Denna slås på manuellt (t.ex. via en knapp) för att aktivera filmläget.
  film:
    name: Filmläge
    icon: mdi:filmstrip
  # Denna slås på automatiskt när en film faktiskt spelas.
  # Används för att styra belysning etc.
  film_spelar:
    name: Film spelar
    icon: mdi:filmstrip

# --- Automation för att hantera filmläget ---
# Denna automation hanterar både när en film startar och stoppas.
automation:
  - alias: Filmläge hantering
    id: filmlage_hantering
    triggers:
      # Triggar när mediaspelaren har varit i 'playing'-läge i 10 sekunder.
      - trigger: state
        entity_id: media_player.allrum
        to: 'playing'
        for:
          seconds: 10
        id: film_startar

      # Triggar när mediaspelaren har varit pausad/stoppad i 5 sekunder.
      - trigger: state
        entity_id: media_player.allrum
        from: 'playing'
        for:
          seconds: 5
        id: film_stoppar

      # Triggar också direkt om det övergripande filmläget stängs av.
      - trigger: state
        entity_id: input_boolean.film
        to: 'off'
        id: filmlage_av
    actions:
      - choose:
          # --- SEKVENS NÄR EN FILM STARTAR ---
          - conditions:
              # Villkor 1: Automationen måste ha triggats av att filmen startade.
              - condition: trigger
                id: film_startar
              # Villkor 2: Det övergripande filmläget måste vara aktivt.
              - condition: state
                entity_id: input_boolean.film
                state: 'on'
            sequence:
              # Slår på 'film_spelar'-hjälparen.
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.film_spelar

          # --- SEKVENS NÄR EN FILM STOPPAR ELLER FILMLÄGET STÄNGS AV ---
          - conditions:
              # Körs om någon av de andra två triggers har aktiverats.
              - condition: trigger
                id:
                  - film_stoppar
                  - filmlage_av
            sequence:
              # Slår av 'film_spelar'-hjälparen.
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.film_spelar