# =================================================================
# LOGIK FÖR BELYSNING
# =================================================================
# All logik för att styra belysningen i studion.
# -----------------------------------------------------------------

# --- Profil för adaptiv belysning ---
adaptive_lighting:
  - name: Studio
    lights:
      - light.linas_skrivbord
      - light.studio_vit_skarmlampa
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
    adapt_only_on_bare_turn_on: true

# --- Inställning för ljusnivå ---
# Flyttad till UI
#input_number:
#  studio_light_level:
#    name: Ljusstyrka utomhus för belysning studio
#    min: 0
#    max: 1000
#    step: 50
#    unit_of_measurement: lx
#    icon: mdi:lightbulb-on

# --- Sensorer som styr automationen ---
template:
  - binary_sensor:
      # Steg 1: Är det mörkt nog ute för att tända?
      - name: studio_belysning_lightlevel
        unique_id: studio_belysning_lightlevel
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0) < states('input_number.studio_light_level') | float(0) }}
#      
      # Steg 2: Den slutgiltiga kontrollsensorn som triggar automationen.
      - name: studio_belysning_automation_control
        unique_id: studio_belysning_automation_control
        state: >
          {{ is_state('binary_sensor.studio_belysning_lightlevel', 'on')
            and is_state('input_boolean.sovdags', 'off') }}

# --- Automationen som tänder/släcker ---
automation:
  - alias: Studio belysning
    id: studio_belysning
    triggers:
      - trigger: state
        entity_id: binary_sensor.studio_belysning_automation_control
      - trigger: homeassistant
        event: start
    actions:
      # Steg 1: Styr fönsterlamporna baserat på kontrollsensorn.
      - action: "light.turn_{{ iif(states('binary_sensor.studio_belysning_automation_control') == 'on', 'on', 'off') }}"
        target:
          entity_id:
            - light.studio_vit_skarmlampa
            - light.linas_skrivbord