# packages/emhass/EMHASS_preprocess.yaml
#
# Förbehandling av effekt m.m. (EXAKT som i din fil, bara flyttat)

sensor:
  - platform: statistics
    name: solar_power_photovoltaics_filtered
    unique_id: solar_power_photovoltaics_filtered
    entity_id: sensor.solar_power_photovoltaics
    state_characteristic: average_linear
    max_age:
      minutes: 5

  - platform: statistics
    name: power_production_sannesholma_2181_filtered
    unique_id: power_production_sannesholma_2181_filtered
    entity_id: sensor.power_production_sannesholma_2181
    state_characteristic: average_linear
    max_age:
      minutes: 5

  - platform: filter
    name: power_sannesholma_2181_no_var_loads_filtered_test
    unique_id: power_sannesholma_2181_no_var_loads_filtered_test
    entity_id: sensor.power_sannesholma_2181_no_var_loads
    filters:
      - filter: range                     # klipp orimliga toppar
        lower_bound: 0
        upper_bound: 5000                 # kan sänkas till 4500 om du vill vara striktare
      - filter: outlier                   # dämpa enstaka hopp
        window_size: 8                    # ≈2 h om du har 15-min data
        radius: 1200
      - filter: time_simple_moving_average
        window_size: "00:01"              # ~45 min
        precision: 0
#
  - platform: filter
    name: power_sannesholma_2181_no_var_loads_filtered_test_2
    unique_id: power_sannesholma_2181_no_var_loads_filtered_test_2
    entity_id: sensor.power_sannesholma_2181_no_var_loads
    filters:
      - filter: range                     # klipp orimliga toppar
        lower_bound: 0
        upper_bound: 5000                 # kan sänkas till 4500 om du vill vara striktare
      - filter: outlier                   # dämpa enstaka hopp
        window_size: 8                    # ≈2 h om du har 15-min data
        radius: 1200
      - filter: time_simple_moving_average
        window_size: "00:00:30"              # ~45 min
        precision: 0
        #
template:
  - sensor:
      - name: ehl75l9h_power_watt
        unique_id: ehl75l9h_power_watt
        availability: >
          {{ is_number(states('sensor.ehl75l9h_power')) }}
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {{ ( states('sensor.ehl75l9h_power') | float('naan') * 1000 ) | round(0) }}

      - name: power_sannesholma_2181_no_var_loads
        unique_id: power_sannesholma_2181_no_var_loads
        availability: >
          {{ is_number(states('sensor.power_usage'))
            and is_number(states('sensor.heatpump_power')) }}
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {{ max(0,( states('sensor.power_usage') | float(0)
          - states('sensor.heatpump_power') | float(0)
          - states('sensor.ehl75l9h_power_watt') | float(0)
          - states('sensor.shellyplug_s_c8c9a3a4f80a_power') | float(0)
          - states('sensor.heatpump_addheat1_power') | float(0)
          - states('sensor.ac_effekt') | float(0)
          ) | round(0) ) }}

      - name: power_sannesholma_2181_no_var_loads_filtered
        unique_id: power_sannesholma_2181_no_var_loads_filtered
        availability: >
          {{ is_number(states('sensor.power_usage_filtered'))
            and is_number(states('sensor.heatpump_power')) }}
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {{ max(0,( states('sensor.power_usage_filtered') | float('naan')
            - states('sensor.heatpump_power') | float(0)
            - states('sensor.ehl75l9h_power_watt') | float(0)
            - states('sensor.shellyplug_s_c8c9a3a4f80a_power') | float(0)
            - states('sensor.heatpump_addheat1_power') | float(0)
            - states('sensor.ac_effekt') | float(0)
          ) | round(0) ) }}

