shell_command:
  publish_data_def2: >
    curl -i -H "Content-Type:application/json" -X POST -d '{
      "num_def_loads": 3,
      "custom_deferrable_forecast_id": [
        {"entity_id": "sensor.p_deferrable0","unit_of_measurement": "W", "friendly_name": "Värmepump"},
        {"entity_id": "sensor.p_deferrable1","unit_of_measurement": "W", "friendly_name": "Deferrable Load 1"},
        {"entity_id": "sensor.p_deferrable2","unit_of_measurement": "W", "friendly_name": "Deferrable Load 2"}
        ],
      "custom_unit_load_cost_id": {"entity_id": "sensor.unit_load_cost","unit_of_measurement": "SEK/kWh", "friendly_name": "Unit load cost"},
      "custom_unit_prod_price_id": {"entity_id": "sensor.unit_prod_price","unit_of_measurement": "SEK/kWh", "friendly_name": "Unit prod price"}
      }' http://localhost:5000/action/publish-data

automation:
  - alias: EMHASS publicera data
    id: EMHASS publicera data
    trigger:
      - platform: homeassistant
        event: start
      - platform: time_pattern
        minutes: /1
    action:
      - service: shell_command.publish_data_def2