################# Circadian ##############################################
adaptive_lighting:
  - name: Allrum
    lights:
      - light.allrum_tak_1
      - light.allrum_tak_2
      - light.allrum_tak_3
      - light.allrum_laslampa
      - light.allrum_klotlampa
    transition: 30
    sleep_transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 30
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
    adapt_only_on_bare_turn_on: true
  #
  - name: Allrum belysning filament
    lights:
      - light.allrum_fonster_betong
      - light.allrum_huslampa
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 35
    sleep_brightness: 1
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
#
light:
  - platform: group
    name: Allrum grupp
    unique_id: allrum_grupp
    entities:
      - light.allrum_tak_1
      - light.allrum_tak_2
      - light.allrum_tak_3
      - light.allrum_laslampa
      - light.allrum_klotlampa
      - light.allrum_fonster_betong
      - light.allrum_huslampa
      # Ljusstakar
#      - light.ac_000000a_1
#      - light.ac0000001_4
      # Tomte
#      - light.ac_0000001_2
      # Julgran
#      - light.ac_0000002_4
#
#
input_number:
#
  allrum_light_level:
    name: Ljusstyrka allrum för belysning
    min: 0
    max: 100
    step: 1
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
  allrum_huslampa_light_level:
    name: Ljusstyrka allrum för belysning huslampa
    min: 0
    max: 2000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
  allrum_fonster_light_level:
    name: Ljusstyrka allrum för fönsterbelysning
    min: 0
    max: 2000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
#
template:
#
#
#
  - trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: allrum_knapp
          event: 1004
    binary_sensor:
      - name: Allrum läsning
        unique_id: Allrum läsning
        auto_off: 60
        state: "true"
#
  - binary_sensor:
      #### Filament ##############
      # Fömsterbeysning ljusstyrka
      - name: allrum_belysning_filament_lightlevel
        unique_id: allrum_belysning_filament_lightlevel
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0.0) < states('input_number.allrum_fonster_light_level') | float(0.0) }}
      # Huslampa
      - name: allrum_huslampa_lightlevel
        unique_id: allrum_huslampa_lightlevel
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float(0.0) < states('input_number.allrum_huslampa_light_level') | float(0.0) }}
      #
      # Belysning filament
      - name: allrum_belysning_filament_automation_control
        unique_id: allrum_belysning_filament_automation_control
        state: >
          {{ is_state('binary_sensor.allrum_belysning_filament_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
      #
      # Huslampa automationskontroll
      - name: allrum_huslampa_automation_control
        unique_id: allrum_huslampa_automation_control
        state: >
          {{ is_state('binary_sensor.allrum_huslampa_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
      #
      #### Tak #########################################
      #
      - name: allrum_lightlevel
        unique_id: allrum_lightlevel
        device_class: light
        state: >
          {{ ( states('sensor.allrum_hue_motion_sensor_light_level') | float > states('input_number.allrum_light_level') | float
            and is_state('light.allrum_tak_1', 'off') ) 
            or ( is_state('binary_sensor.allrum_lightlevel', 'on')
            and is_state('light.allrum_tak_1', 'on') ) }}
      #
      ### Närvarostyrd belysning i tak
      - name: allrum_presence_light_automation_control
        unique_id: allrum_presence_light_automation_control
        state: >
          {{ is_state('binary_sensor.allrum_presence', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('binary_sensor.allrum_lightlevel', 'off') }}
      #
      # Belysning i hall
      - name: allrum_belysning_hall_automation_control
        unique_id: allrum_belysning_hall_automation_control
        state: >
          {{ ( is_state('binary_sensor.allrum_presence_hall', 'on')
            or is_state('binary_sensor.mikaels_rum_narvaro', 'on') )
            and is_state('input_boolean.film_spelar', 'off') }}
      #
      # Belysning läslampa
      - name: allrum_belysning_laslampa_automation_control
        unique_id: allrum_belysning_laslampa_automation_control
        state: >
          {{ is_state('binary_sensor.allrum_presence_sensor_fp2', 'on') and is_state('input_boolean.film_spelar', 'off') }}
      # Test med att köra läslampa med övriga lampor 
      #
      - name: allrum_presence
        unique_id: allrum_presence
        delay_off:
          seconds: 30
        state: >
          {{ is_state('binary_sensor.allrum_presence_sensor_fp2', 'on') or is_state('binary_sensor.allrum_rorelsesensor', 'on') }}
      #
      #
      - name: allrum_presence_hall
        unique_id: allrum_presence_hall
        delay_off:
          seconds: 90
        state: >
          {{ is_state('binary_sensor.allrum_rorelsesensor', 'on') }}
      #
#
#
automation:
#
#
  - alias: Allrum belysning fönster
    id: Allrum belysning fönster
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_belysning_filament_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.allrum_belysning_filament_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.allrum_belysning_filament_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.allrum_fonster_betong
          - light.allrum_klotlampa
#
#
  - alias: Allrum belysning tak
    id: Allrum belysning tak
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_presence_light_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.allrum_presence_light_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.allrum_presence_light_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.allrum_tak_1
          - light.allrum_tak_2
#
#
  - alias: Allrum belysning hall
    id: Allrum belysning hall
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_belysning_hall_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.allrum_belysning_hall_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.allrum_belysning_hall_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.allrum_tak_3
#
  - alias: Allrum belysning läslampa
    id: Allrum belysning läslampa
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_belysning_laslampa_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.allrum_belysning_laslampa_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.allrum_belysning_laslampa_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.allrum_laslampa
#
  - alias: Allrum huslampa
    id: Allrum huslampa
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_huslampa_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.allrum_huslampa_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.allrum_huslampa_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.allrum_huslampa
          # Tomte
#          - light.ac_0000001_2
          # Julgran
#          - light.ac_0000002_4
#
  - alias: Allrum knapp vid fåtölj
    id: Allrum knapp vid fåtölj
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: allrum_knapp
          event: 1002
    action:
      - service: light.toggle
        target:
          entity_id: light.allrum
#
#
  - alias: Allrum knapp vid tv
    id: Allrum knapp vid tv
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: allrum_smart_switch
    action:
      - choose:
        #
        # Double press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1004 }}'
            - condition: state
              entity_id: input_boolean.film
              state: "off"
          sequence:
            - service: input_boolean.turn_on
              entity_id: input_boolean.film
        #
        # Short press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1002 }}'
          sequence:
            - service: >
                {% if is_state('media_player.allrum', 'playing') %}
                media_player.media_pause
                {% else %}
                media_player.media_play
                {% endif %}
              entity_id:
                - media_player.allrum
        #
        # Long press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1001 }}'
          sequence:
            - service: input_boolean.toggle
              entity_id: input_boolean.film_spelar
#