# =================================================================
# HUVUDFIL FÖR ALLRUMMET
# =================================================================
# Denna fil är den centrala punkten för allt som rör allrummet.
# Den slår ihop innehållet från alla .yaml-filer i undermappen /allrum/
# -----------------------------------------------------------------

adaptive_lighting: !include_dir_merge_named allrum
light: !include_dir_merge_named allrum
input_boolean: !include_dir_merge_named allrum
input_number: !include_dir_merge_named allrum
template: !include_dir_merge_named allrum
automation: !include_dir_merge_named allrum