#
automation:
  - alias: Perform Daily Backup
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      condition: time # Perform backup every day except Mondays.
      weekday:
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
    action:
      service: auto_backup.backup_full
      data_template:
        name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
        keep_days: 7
#
  - alias: Perform Weekly Backup
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      condition: time # On Mondays perform a weekly backup
      weekday:
        - mon
    action:
      service: auto_backup.backup_full
      data_template:
        name: "WeeklyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
        keep_days: 56
#
  - alias: "Notify backup Failure"
    trigger:
      platform: event
      event_type: auto_backup.backup_failed
    action:
      service: persistent_notification.create
      data_template:
        title: "Backup Failed."
        message: "Name: {{ trigger.event.data.name }}\nError: {{ trigger.event.data.error }}"