# =================================================================
# KONFIGURATION FÖR BADRUMMET
# =================================================================
# All logik för att styra belysningen i badrummet.
#
# OBS! Lampor styrs via styrningsgrupp i UI:
#  - light.badrum_styrning
#
# OBS! Styrparametrar hanteras via UI (Helpers):
#  - input_number.badrum_light_level
# -----------------------------------------------------------------


# =================================================================
# ADAPTIVE LIGHTING-PROFIL
# =================================================================
# Justerar automatiskt färgtemperatur och ljusstyrka på lamporna
# baserat på dygnsrytm (solens position).
# -----------------------------------------------------------------
adaptive_lighting:
  - name: Badrum
    lights:
      - light.badrum_spegel
      - light.badrum_tak
    prefer_rgb_color: false
    transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
    adapt_only_on_bare_turn_on: true


# =================================================================
# TEMPLATE-SENSORER
# =================================================================
template:
  - binary_sensor:
      # =============================================================
      # LJUSNIVÅ (INNE)
      # =============================================================
      # Steg 1: Är det för ljust inne för att tända belysningen?
      #
      # on  = för ljust (tänd inte)
      # off = mörkt nog (OK att tända)
      #
      # Inkluderar spärrlogik så att lamporna inte släcker sig själva
      # när de precis har tänts och luxvärdet hoppar upp.
      # -------------------------------------------------------------
      - name: badrum_lightlevel
        unique_id: badrum_lightlevel
        delay_on:
          minutes: 5
        state: >
          {{
            (
              (states('sensor.badrum_hue_motion_sensor_light_level') | float(9999))
              > (states('input_number.badrum_light_level') | float(0))
              and is_state('light.badrum_styrning', 'off')
            )
            or
            (
              is_state('binary_sensor.badrum_lightlevel', 'on')
              and is_state('light.badrum_styrning', 'on')
            )
          }}

      # =============================================================
      # NÄRVARO
      # =============================================================
      # Steg 1: Närvaro med fördröjning (undviker "fladder")
      - name: badrum_presence
        unique_id: badrum_presence
        device_class: motion
        delay_off:
          minutes: 7
        state: >
          {{ is_state('binary_sensor.badrum_hue_motion_sensor_motion', 'on') }}

      # =============================================================
      # AUTOMATION CONTROL
      # =============================================================
      # Steg 2: Slutlig kontrollsensor som triggar automationen
      - name: badrum_presence_light_automation_control
        unique_id: badrum_presence_light_automation_control
        state: >
          {{ is_state('binary_sensor.badrum_presence', 'on')
            and is_state('binary_sensor.badrum_lightlevel', 'off') }}


# =================================================================
# AUTOMATION
# =================================================================
automation:
  - alias: Badrum belysning
    id: badrum_belysning
    mode: single
    triggers:
      - trigger: state
        entity_id: binary_sensor.badrum_presence_light_automation_control
      - trigger: homeassistant
        event: start
    actions:
      - action: "light.turn_{{ states('binary_sensor.badrum_presence_light_automation_control') }}"
        target:
          entity_id: light.badrum_styrning