################# Circadian ##############################################
adaptive_lighting:
  - name: Badrum
    lights:
    - light.badrum
    prefer_rgb_color: false
    transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
input_number:
  badrum_light_level:
    name: Ljusstyrka badrum för belysning
    min: 0
    max: 200
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
template:
  - binary_sensor:
      ### Light level
      - name: badrum_lightlevel
        unique_id: badrum_lightlevel
        device_class: light
        delay_on:
          minutes: 5
        state: >
          {{ ( states('sensor.badrum_hue_motion_sensor_light_level') | float(0.0) > states('input_number.badrum_light_level') | float(0.0)
            and is_state('light.badrum', 'off') )
            or ( is_state('binary_sensor.badrum_lightlevel', 'on')
            and is_state('light.badrum', 'on') ) }}
      ### Närvaro
      - name: badrum_presence
        unique_id: badrum_presence
        device_class: motion
        delay_off:
          minutes: 10
        state: >
          {{ is_state('binary_sensor.badrum_hue_motion_sensor_motion', 'on') }}
      ### Närvarostyrd belysning
      - name: badrum_presence_light_automation_control
        state: >
          {{ is_state('binary_sensor.badrum_presence', 'on')
              and is_state('binary_sensor.badrum_lightlevel', 'off') }}
#
automation:
#
  - alias: Badrum belysning
    id: Badrum belysning
    trigger:
    - platform: state
      entity_id: binary_sensor.badrum_presence_light_automation_control
    - platform: homeassistant
      event: start
    action:
    - service: >
        {% if is_state('binary_sensor.badrum_presence_light_automation_control', 'on') %}
        light.turn_on
        {% elif is_state('binary_sensor.badrum_presence_light_automation_control', 'off') %}
        light.turn_off
        {% endif %}
      entity_id:
      - light.badrum