################# Circadian ##############################################
adaptive_lighting:
  - name: Barnrum
    lights:
    - light.barnrum_skank
    - light.barnrum_fonster_1
    - light.barnrum_fonster_2
    - light.barnrum_tak
    # Julstjärna
#    - light.barnrum_fonster
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
light:
  - platform: group
    name: barnrum_grupp
    unique_id: barnrum_grupp
    entities:
      - light.barnrum_skank
      - light.barnrum_fonster_1
      - light.barnrum_fonster_2
      - light.barnrum_tak
      # Julstjärna
#      - light.barnrum_fonster
      # Ljusstake
#      - light.barnrum_ljusstake
#
input_boolean:
  barnrum_gaster:
    name: Gäster barnrum
#
#
input_number:
  barnrum_light_level:
    name: Ljusstyrka utomhus för belysning barnrum
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
  #
  barnrum_fonster_light_level:
    name: Ljusstyrka utomhus för belysning i fönster barnrum
    min: 0
    max: 1000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
climate:
  - platform: generic_thermostat
    name: Barnrum värmegolv
    unique_id: Barnrum värmegolv
    cold_tolerance: 0.0
    hot_tolerance: 0.2
    precision: 0.1
    heater: switch.barnrum_varmegolv
    target_sensor: sensor.barnrum_temperature
    min_temp: 7
#
template:
  - binary_sensor:
      # Ljus
      - name: barnrum_belysning_lightlevel
        unique_id: barnrum_belysning_lightlevel
        delay_off:
          minutes: 15
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.barnrum_light_level') | float }}
      #
      - name: barnrum_belysning_fonster_lightlevel
        unique_id: barnrum_belysning_fonster_lightlevel
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.barnrum_fonster_light_level') | float }}
      # 
      - name: barnrum_belysning_automation_control
        unique_id: barnrum_belysning_automation_control
        state: >
          {{ ( is_state('binary_sensor.barnrum_belysning_lightlevel', 'on')
          and is_state('input_boolean.sovdags', 'off') )
          or ( is_state('binary_sensor.barnrum_belysning_lightlevel', 'on')
          and is_state('input_boolean.barnrum_gaster', 'on') ) }}
      #
      - name: barnrum_belysning_fonster_automation_control
        unique_id: barnrum_belysning_fonster_automation_control
        state: >
          {{ ( is_state('binary_sensor.barnrum_belysning_fonster_lightlevel', 'on')
          and is_state('input_boolean.sovdags', 'off') )
          or ( is_state('binary_sensor.barnrum_belysning_fonster_lightlevel', 'on')
          and is_state('input_boolean.barnrum_gaster', 'on') ) }}
#
automation:
#
  - alias: Barnrum belysning
    id: Barnrum belysning
    trigger:
    - platform: state
      entity_id: binary_sensor.barnrum_belysning_automation_control
    - platform: homeassistant
      event: start
    action:
    - service: >
        {% if is_state('binary_sensor.barnrum_belysning_automation_control', 'on') %}
        light.turn_on
        {% elif is_state('binary_sensor.barnrum_belysning_automation_control', 'off') %}
        light.turn_off
        {% endif %}
      entity_id:
      - light.barnrum_skank
  #
  #
  - alias: Barnrum belysning fönster
    id: Barnrum belysning fönster
    trigger:
    - platform: state
      entity_id: binary_sensor.barnrum_belysning_fonster_automation_control
    - platform: homeassistant
      event: start
    action:
    - service: >
        {% if is_state('binary_sensor.barnrum_belysning_fonster_automation_control', 'on') %}
        light.turn_on
        {% elif is_state('binary_sensor.barnrum_belysning_fonster_automation_control', 'off') %}
        light.turn_off
        {% endif %}
      entity_id:
      - light.barnrum_fonster_1
      - light.barnrum_fonster_2
#      - light.barnrum_fonster
#      - light.barnrum_ljusstake
#
  - alias: Barnrum värme
    id: Barnrum värme
    trigger:
      - platform: state
        entity_id: binary_sensor.varmegolv_block
      - platform: homeassistant
        event: start
    action:
      - choose:
        #
        - conditions:
            - condition: state
              state: 'on'
              entity_id: binary_sensor.varmegolv_block
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.barnrum_varmegolv
              data:
                hvac_mode: 'off'
        #
        - conditions:
            - condition: state
              state: 'off'
              entity_id: binary_sensor.varmegolv_block
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.barnrum_varmegolv
              data:
                hvac_mode: 'heat'