#
automation:
#
  - alias: Barnrum brandvarnare
    id: barnrum_brandvarnare
    triggers:
      - trigger: state
        entity_id: binary_sensor.barnrum_brandvarnare_smoke
        to:
          - 'on'
          - 'off'
    actions:
      - action: "siren.turn_{{ trigger.to_state.state }}"
        target:
          entity_id:
            - siren.allrum_brandvarnare_alarm
            - siren.allrum_hall_brandvarnare_alarm
            - siren.snickarboa_brandvarnare_alarm
            - siren.tvattstuga_brandvarnare_alarm
#
  - alias: Allrum brandvarnare
    id: allrum_brandvarnare
    # Toppnivå-nyckeln är nu 'triggers' (plural).
    triggers:
      # Nyckeln för typ av trigger är nu 'trigger' (singular).
      - trigger: state
        entity_id: binary_sensor.allrum_brandvarnare_smoke
        to:
          - 'on'
          - 'off'
    # Toppnivå-nyckeln för handlingar är nu 'actions' (plural).
    actions:
      # Detta är den nya syntaxen för HA 2024.10+
      - action: "siren.turn_{{ trigger.to_state.state }}"
        target:
          entity_id:
            - siren.allrum_hall_brandvarnare_alarm
            - siren.snickarboa_brandvarnare_alarm
            - siren.tvattstuga_brandvarnare_alarm
#
  - alias: Allrum hall brandvarnare
    id: allrum_hall_brandvarnare
    trigger:
      - platform: state
        entity_id: binary_sensor.allrum_hall_brandvarnare_smoke
        to:
          - 'on'
          - 'off'
    action:
      - action: "siren.turn_{{ trigger.to_state.state }}"
        target:
          entity_id:
            - siren.allrum_brandvarnare_alarm
            - siren.snickarboa_brandvarnare_alarm
            - siren.tvattstuga_brandvarnare_alarm
#
  - alias: Snickarboa brandvarnare
    id: snickarboa_brandvarnare
    trigger:
      - platform: state
        entity_id: binary_sensor.snickarboa_brandvarnare_smoke
        to:
          - 'on'
          - 'off'
    action:
      - action: "siren.turn_{{ trigger.to_state.state }}"
        target:
          entity_id:
            - siren.allrum_brandvarnare_alarm
            - siren.allrum_hall_brandvarnare_alarm
            - siren.tvattstuga_brandvarnare_alarm
#