utility_meter:
  diskmaskin_timme:
    unique_id: diskmaskin_timme
    source: sensor.diskmaskin_consumption
    cycle: hourly
  diskmaskin_dag:
    unique_id: diskmaskin_dag
    source: sensor.diskmaskin_consumption
    cycle: daily
  diskmaskin_vecka:
    unique_id: diskmaskin_vecka
    source: sensor.diskmaskin_consumption
    cycle: weekly
  diskmaskin_manad:
    unique_id: diskmaskin_manad
    source: sensor.diskmaskin_consumption
    cycle: monthly
  diskmaskin_ar:
    unique_id: diskmaskin_ar
    source: sensor.diskmaskin_consumption
    cycle: yearly
#
  diskmaskin_dag_kostnad:
    unique_id: diskmaskin_dag_kostnad
    source: sensor.diskmaskin_timme_kostnad
    cycle: daily
  diskmaskin_manad_kostnad:
    unique_id: diskmaskin_manad_kostnad
    source: sensor.diskmaskin_timme_kostnad
    cycle: monthly
  diskmaskin_ar_kostnad:
    unique_id: diskmaskin_ar_kostnad
    source: sensor.diskmaskin_timme_kostnad
    cycle: yearly
#
#sensor:
#  - platform: template
#    sensors:
      ###
#      diskmaskin_timme_kostnad:
#        friendly_name: "Kostnad"
#        unit_of_measurement: "SEK"
#        value_template: "{{ ( states('sensor.diskmaskin_timme') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"
#
#binary_sensor:
# Determine when the dishwasher has a load running.
#  - platform: template
#    sensors:
#      diskmaskin:
#        friendly_name: "Diskmaskin"
#        delay_off:
#          minutes: 5
#        delay_on:
#          seconds: 30
#        value_template: >-
#          {{ states('sensor.diskmaskin_power')|float > 1 }}
#        icon_template: mdi:dishwasher
#
template:
  - sensor:
      # Diskmaskin
      - name: diskmaskin_timme_kostnad
        unique_id: diskmaskin_timme_kostnad
        unit_of_measurement: "SEK"
#        state_class: measurement
        device_class: monetary
        availability: "{{ is_number(states('sensor.diskmaskin_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.diskmaskin_timme') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"


  - binary_sensor:
      - name: diskmaskin
        unique_id: diskmaskin
        delay_off:
          minutes: 5
        delay_on:
          seconds: 30
        state: >
          {{ states('sensor.diskmaskin_power') | float > 1 }}
#
automation:
- alias: Diskmaskin klar
  trigger:
    platform: state
    entity_id: binary_sensor.diskmaskin
    from: "on"
    to: "off"
  action:
  - service: persistent_notification.create
    data_template:
      message: "Diskmaskin"
      title: "Diskmaskinen är klar"
  - service: notify.mobile_app_sm_n975f
    data_template:
      message: "Diskmaskin klar"
      title: "Diskmaskinen är klar"
  - service: notify.mobile_app_sm_g998b
    data_template:
      message: "Diskmaskin klar"
      title: "Diskmaskinen är klar"
#