utility_meter:
  #
  ###################
  ### Förbrukning ###
  ###################
  diskmaskin_timme:
    unique_id: diskmaskin_timme
    source: sensor.diskmaskin_consumption
    periodically_resetting: false
    cycle: hourly
  diskmaskin_dag:
    unique_id: diskmaskin_dag
    source: sensor.diskmaskin_consumption
    periodically_resetting: false
    cycle: daily
  diskmaskin_manad:
    unique_id: diskmaskin_manad
    source: sensor.diskmaskin_consumption
    periodically_resetting: false
    cycle: monthly
  diskmaskin_ar:
    unique_id: diskmaskin_ar
    source: sensor.diskmaskin_consumption
    periodically_resetting: false
    cycle: yearly
  #
#
#
template:
  - sensor:
      #### Diskar ###########################
      #######################################
  - binary_sensor:
      - name: diskmaskin
        unique_id: diskmaskin
        delay_off:
          minutes: 5
        delay_on:
          seconds: 30
        state: >
          {{ states('sensor.diskmaskin_power') | float(0.0) > 1 }}
#
      #
automation:
  #
  - alias: Diskmaskin klar
    id: Diskmaskin klar
    trigger:
      platform: state
      entity_id: binary_sensor.diskmaskin
      from: "on"
      to: "off"
    action:
    - service: persistent_notification.create
      data_template:
        message: "Diskmaskin"
        title: "Diskmaskinen är klar"
    - service: notify.mobile_app_mikael_iphone
      data_template:
        message: "Diskmaskin klar"
        title: "Diskmaskinen är klar"
    - service: notify.mobile_app_lina_iphone
      data_template:
        message: "Diskmaskin klar"
        title: "Diskmaskinen är klar"
  #