# Easyserv värmepump REST API
#
sensor:
  - platform: rest
    resource: !secret easyserv
    verify_ssl: false
    name: heatpump
    json_attributes:
      - HotwaterTemp1
      - HotwaterTemp2
      - IndoorTemp
      - OutdoorTemp
      - RadiatorForwardTemp
      - RadiatorReturnTemp
      - HeatCarrierInTemp
      - HeatCarrierOutTemp
      - BrineInTemp
      - BrineOutTemp
      - HotGasTemp
      - CompressorState
      - ColdCircuitPumpState
      - HeatCircuitPumpState
      - RadiatorPumpState
      - AddHeat2State
      - AddHeat1State
      - SwitchValve1State
      - HeatingSetpointTemp
      - HotwaterSetpointTemp
      - AddHeatLevelPercent
      - SumAlarm
      - LoadL1
      - LoadL2
      - LoadL3
    value_template: '{{ value_json.CompressorState }}'
#
#
  - platform: integration
    source: sensor.heatpump_compressor_real_power
    name: heatpump_compressor_consumption
    unit_prefix: k
    round: 2
    method: left
#
  - platform: integration
    source: sensor.heatpump_coldcircuitpump_real_power
    name: heatpump_coldcircuitpump_consumption
    unit_prefix: k
    round: 2
    method: left
#
  - platform: integration
    source: sensor.heatpump_hotwater_power
    name: heatpump_hotwater_consumption
    unit_prefix: k
    round: 2
    method: left
#
  - platform: integration
    source: sensor.heatpump_heat_power
    name: heatpump_heat_consumption
    unit_prefix: k
    round: 2
    method: left
#
  - platform: history_stats
    name: heatpump_compressor_today
    entity_id: binary_sensor.heatpump_compressor_state
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
#
# binary_sensor.heatpump_coldcircuitpump_state
  - platform: history_stats
    name: heatpump_coldcircuitpump_today
    entity_id: binary_sensor.heatpump_coldcircuitpump_state
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
#
utility_meter:
  heatpump_timme:
    source: sensor.heatpump_consumption
    cycle: hourly
  heatpump_dag:
    source: sensor.heatpump_consumption
    cycle: daily
  heatpump_vecka:
    source: sensor.heatpump_consumption
    cycle: weekly
  heatpump_manad:
    source: sensor.heatpump_consumption
    cycle: monthly
  heatpump_ar:
    source: sensor.heatpump_consumption
    cycle: yearly
  #
  heatpump_timme_kostnad:
    source: sensor.heatpump_kostnad
    cycle: daily
  heatpump_dag_kostnad:
    source: sensor.heatpump_kostnad
    cycle: daily
  heatpump_manad_kostnad:
    source: sensor.heatpump_kostnad
    cycle: monthly
  heatpump_ar_kostnad:
    source: sensor.heatpump_kostnad
    cycle: yearly
#
  heatpump_hotwater_timme:
    source: sensor.heatpump_hotwater_consumption
    cycle: hourly
  heatpump_hotwater_dag:
    source: sensor.heatpump_hotwater_consumption
    cycle: daily
  heatpump_hotwater_vecka:
    source: sensor.heatpump_hotwater_consumption
    cycle: weekly
  heatpump_hotwater_manad:
    source: sensor.heatpump_hotwater_consumption
    cycle: monthly
  heatpump_hotwater_ar:
    source: sensor.heatpump_hotwater_consumption
    cycle: yearly
#
  heatpump_hotwater_timme_kostnad:
    source: sensor.heatpump_hotwater_kostnad
    cycle: daily
  heatpump_hotwater_dag_kostnad:
    source: sensor.heatpump_hotwater_kostnad
    cycle: daily
  heatpump_hotwater_manad_kostnad:
    source: sensor.heatpump_hotwater_kostnad
    cycle: monthly
  heatpump_hotwater_ar_kostnad:
    source: sensor.heatpump_hotwater_kostnad
    cycle: yearly
#
  heatpump_heat_timme:
    source: sensor.heatpump_heat_consumption
    cycle: hourly
  heatpump_heat_dag:
    source: sensor.heatpump_heat_consumption
    cycle: daily
  heatpump_heat_vecka:
    source: sensor.heatpump_heat_consumption
    cycle: weekly
  heatpump_heat_manad:
    source: sensor.heatpump_heat_consumption
    cycle: monthly
  heatpump_heat_ar:
    source: sensor.heatpump_heat_consumption
    cycle: yearly
#
  heatpump_heat_timme_kostnad:
    source: sensor.heatpump_heat_kostnad
    cycle: daily
  heatpump_heat_dag_kostnad:
    source: sensor.heatpump_heat_kostnad
    cycle: daily
  heatpump_heat_manad_kostnad:
    source: sensor.heatpump_heat_kostnad
    cycle: monthly
  heatpump_heat_ar_kostnad:
    source: sensor.heatpump_heat_kostnad
    cycle: yearly
#
binary_sensor:
  #
  - platform: template
    sensors:
      heatpump_compressor_state:
        friendly_name: "Kompressor"
        unique_id: heatpump_compressor_state
        value_template: >-
          {{ state_attr('sensor.heatpump', 'CompressorState') > 0 }}
      #
      heatpump_switchvalve_state:
        friendly_name: "Växelventil"
        unique_id: heatpump_switchvalve_state
        value_template: >-
          {{ state_attr('sensor.heatpump', 'SwitchValve1State') > 0 }}
      #
      heatpump_radiatorpump_state:
        friendly_name: "Radiatorpump"
        unique_id: heatpump_radiatorpump_state
        value_template: >-
          {{ state_attr('sensor.heatpump', 'RadiatorPumpState') > 0 }}
      #
      heatpump_coldcircuitpump_state:
        friendly_name: "Köldbärarpump"
        unique_id: heatpump_coldcircuitpump_state
        value_template: >-
          {{ state_attr('sensor.heatpump', 'ColdCircuitPumpState') > 0 }}
      #
      heatpump_heatcircuitpumpstate_state:
        friendly_name: "Värmekretspump"
        unique_id: heatpump_heatcircuitpumpstate_state
        value_template: >-
          {{ state_attr('sensor.heatpump', 'HeatCircuitPumpState') > 0 }}
      #
      heatpump_sumalarm:
        friendly_name: "Summalarm"
        unique_id: heatpump_sumalarm
        value_template: >-
          {{ state_attr('sensor.heatpump', 'SumAlarm') > 0 }}
#
template:
    sensor:
      # Kompressor
      - name: "Kompressor aktiv effekt P"
        unique_id: heatpump_compressor_real_power
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {% if is_state('binary_sensor.heatpump_compressor_state', 'on') %}
          {{ 400.0 * 5.5 }}
          {% elif is_state('binary_sensor.heatpump_compressor_state', 'off') %}
          0.0
          {% endif %}
      #
      - name: heatpump_consumption_test
        unique_id: heatpump_consumption_test
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        availability: "{{ is_number(states('sensor.heatpump_compressor_today')) and is_number(states('sensor.heatpump_coldcircuitpump_today')) }}"
        state: >
          {{ ( 400.0 * 5.5 * states('sensor.heatpump_compressor_today') | float('nan') / 1000.0 + 400.0 * 1.5 * states('sensor.heatpump_coldcircuitpump_today') | float('nan') / 1000.0 ) | round(3) }}
      #
      # Köldbärarpump aktiv effekt P
      - unique_id: heatpump_coldcircuitpump_real_power
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {% if is_state('binary_sensor.heatpump_coldcircuitpump_state', 'on') %}
          {{ 400.0 * 1.5 }}
          {% elif is_state('binary_sensor.heatpump_coldcircuitpump_state', 'off') %}
          0.0
          {% endif %}
#
      ### Förbrukning
      - name: heatpump_consumption
        unique_id: heatpump_consumption
        unit_of_measurement: "kWh"
        state_class: total_increasing
        availability: "{{ is_number(states('sensor.heatpump_compressor_consumption')) and is_number(states('sensor.heatpump_coldcircuitpump_consumption')) }}"
        state: >
          {{ states('sensor.heatpump_compressor_consumption') | float('not_a_number') + states('sensor.heatpump_coldcircuitpump_consumption') | float('not_a_number') }}
      #
      - name: heatpump_consumption_measurement
        unique_id: heatpump_consumption_measurement
        unit_of_measurement: "kWh"
        state_class: measurement
        state: >
          {{ states('sensor.heatpump_timme') }}
      #
      # Varmvatten
      - name: heatpump_hotwater_power
        unique_id: heatpump_hotwater_power
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {% if is_state('binary_sensor.heatpump_switchvalve_state', 'on') %}
          {{ states('sensor.heatpump_coldcircuitpump_real_power') | float(0.0) + states('sensor.heatpump_compressor_real_power') | float(0.0) }}
          {% elif is_state('binary_sensor.heatpump_switchvalve_state', 'off') %}
          0.0
          {% endif %}
      #
      # Värme
      - name: heatpump_heat_power
        unique_id: heatpump_heat_power
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {% if is_state('binary_sensor.heatpump_switchvalve_state', 'off') %}
          {{ states('sensor.heatpump_coldcircuitpump_real_power') | float(0.0) + states('sensor.heatpump_compressor_real_power') | float(0.0) }}
          {% elif is_state('binary_sensor.heatpump_switchvalve_state', 'on') %}
          0.0
          {% endif %}
      #
      ### Kostnad
      - name: heatpump_kostnad
        unique_id: heatpump_kostnad
        unit_of_measurement: "SEK"
        state_class: measurement
        availability: "{{ is_number(states('sensor.heatpump_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.heatpump_timme') | float('not_a_number') * states('sensor.elpris_totalt_sek') | float('not_a_number') ) | round(3) }}"
#
      - name: heatpump_hotwater_kostnad
        unique_id: heatpump_hotwater_kostnad
        unit_of_measurement: "SEK"
        state_class: measurement
        availability: "{{ is_number(states('sensor.heatpump_hotwater_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.heatpump_hotwater_timme') | float('not_a_number') * states('sensor.elpris_totalt_sek') | float('not_a_number') ) | round(3) }}"
#
      - name: heatpump_heat_kostnad
        unique_id: heatpump_heat_kostnad
        unit_of_measurement: "SEK"
        state_class: measurement
        availability: "{{ is_number(states('sensor.heatpump_heat_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.heatpump_heat_timme') | float('not_a_number') * states('sensor.elpris_totalt_sek') | float('not_a_number') ) | round(3) }}"
#
#       Returledning
      - name: heatpump_radiator_return
        unique_id: heatpump_radiator_return
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'RadiatorReturnTemp') }}"
      # Börvärde
      - name: heatpump_heatinghetpointemp
        unique_id: heatpump_heatinghetpointemp
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'HeatingSetpointTemp') }}"
      # Värmebärare ut
      - name: heatpump_heatcarrier_out
        unique_id: heatpump_heatcarrier_out
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'HeatCarrierOutTemp') }}"
      # Köldbärare in
      - name: heatpump_brine_in
        unique_id: heatpump_brine_in
        state_class: measurement
        device_class: temperature
        unit_of_measurement: "°C"
        state: "{{ state_attr('sensor.heatpump', 'BrineInTemp') }}"
      # Köldbärare ut
      - name: heatpump_brine_out
        unique_id: heatpump_brine_out
        state_class: measurement
        device_class: temperature
        unit_of_measurement: "°C"
        state: "{{ state_attr('sensor.heatpump', 'BrineOutTemp') }}"
      # Hetgas
      - name: heatpump_hotgas
        unique_id: heatpump_hotgas
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'HotGasTemp') }}"
      # Varmvatten
      - name: heatpump_hotwater_temp
        unique_id: heatpump_hotwater_temp
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'HotwaterTemp1') }}"
      # Varmvatten
      - name: heatpump_hotwater_temp_2
        unique_id: heatpump_hotwater_temp_2
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'HotwaterTemp2') }}"
      # Utomhus-temp
      - name: heatpump_outdoor_temp
        unique_id: heatpump_outdoor_temp
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ state_attr('sensor.heatpump', 'OutdoorTemp') }}"
#
homeassistant:
  customize:
    sensor.heatpump_coldcircuitpump_consumption:
      friendly_name: Värmepump köldbärarpump
    sensor.heatpump_compressor_consumption:
      friendly_name: Värmepump kompressor
    sensor.heatpump_timme:
      friendly_name: Värmepump
    sensor.heatpump_heat_consumption:
      friendly_name: Värmepump värmeproduktion
    sensor.heatpump_hotwater_consumption:
      friendly_name: Värmepump varmvattenproduktion