#
input_number:
  electricity_price_sannesholma_2181_input_low:
    name: Elpris lågt
    min: 0
    max: 2
    step: 0.050
    unit_of_measurement: SEK
#    icon: mdi:lightbulb-on
#
template:
  - sensor:
      #
      # Avgift elnät
    - name: avgift_elnat
      unique_id: avgift_elnat
      unit_of_measurement: "Öre/kWh"
      state_class: measurement
      state: "{{ 28.9 }}"
      #
      # Avgift energiskatt
    - name: avgift_energiskatt
      unique_id: avgift_energiskatt
      unit_of_measurement: "Öre/kWh"
      state_class: measurement
      state: "{{ 53.5 }}"
      #
      # Elnätsabonnemang
    - name: elpris_abonnemang
      unique_id: elpris_abonnemang
      unit_of_measurement: "SEK/kWh"
      state_class: measurement
#      availability: "{{ is_number(states('sensor.electricity_price_sannesholma_2181')) }}"
      state: >
        {{ ( 8010 / 13983 ) | round (3) }}
#        {{ ( 612.5 / state_attr('sensor.electricity_price_sannesholma_2181', 'estimated_annual_consumption') ) | round (3) }}
      #
      ############# El totalpris ######################### TODO, hantera om någon faller bort
      # Öre
    - name: elpris_totalt
      unique_id: elpris_totalt
      unit_of_measurement: "Öre/kWh"
      state_class: measurement
      availability: "{{ is_number(states('sensor.electricity_price_sannesholma_2181')) }}"
      state: "{{ ( states('sensor.avgift_elnat') | float + states('sensor.avgift_energiskatt') | float + states('sensor.electricity_price_sannesholma_2181') | float('naan') * 100 ) | round(2) }}"
      # SEK
    - name: elpris_totalt_sek
      unique_id: elpris_totalt_sek
      unit_of_measurement: "SEK/kWh"
      state_class: measurement
      availability: "{{ is_number(states('sensor.electricity_price_sannesholma_2181')) }}"
      state: "{{ ( states('sensor.avgift_elnat') | float / 100 + states('sensor.avgift_energiskatt') | float / 100 + states('sensor.electricity_price_sannesholma_2181') | float('naan') ) | round(3) }}"
#
    - name: elpris_grid
      unique_id: elpris_grid
      unit_of_measurement: "SEK/kWh"
      state_class: measurement
      availability: >
        {{ is_number(states('sensor.avgift_elnat'))
        and is_number(states('sensor.avgift_energiskatt')) }}
      state: >
        {{ ( states('sensor.avgift_elnat') | float('naan') / 100
        + states('sensor.avgift_energiskatt') | float('naan') / 100 ) | round(3) }}
      #
    - name: elpris_produktion
      unique_id: elpris_produktion
      unit_of_measurement: "SEK/kWh"
      state_class: measurement
      availability: "{{ is_number(states('sensor.elpris')) }}"
      state: "{{ ( states('sensor.elpris') | float + 0.6 ) | round(3) }}"
      #
    - name: elpris_natnytta
      unique_id: elpris_natnytta
      unit_of_measurement: "SEK/kWh"
      state_class: measurement
      state: "{{ 0.047 }}"
      #
      # Prisnivå
    - name: elpris_price_level
      unique_id: elpris_price_level
      state: >
        {{ state_attr('sensor.electricity_price_sannesholma_2181', 'price_level') }}
#
  - binary_sensor:
#
        # Maxpris
      - name: electricity_price_sannesholma_2181_max
        unique_id: electricity_price_sannesholma_2181_max
        delay_on:
          minutes: 1
        state: >
          {{ states('sensor.electricity_price_sannesholma_2181') | float(0.0) == state_attr('sensor.electricity_price_sannesholma_2181', 'max_price') | float(0.1) }}
#          {{ states('sensor.elpris') | float(0.0) == state_attr('sensor.elpris', 'max') | float(0.1) }}
        #
        # Max 4
      - name: electricity_price_sannesholma_2181_max_4
        unique_id: electricity_price_sannesholma_2181_max_4
        delay_on:
          seconds: 5
        state: >
          {{ ( states('sensor.elpris') | float(0.0) == ( state_attr('sensor.elpris', 'today') | sort(reverse=true))[0] )
            or ( states('sensor.elpris') | float(0.0) == ( state_attr('sensor.elpris', 'today') | sort(reverse=true))[1] )
            or ( states('sensor.elpris') | float(0.0) == ( state_attr('sensor.elpris', 'today') | sort(reverse=true))[2] )
            or ( states('sensor.elpris') | float(0.0) == ( state_attr('sensor.elpris', 'today') | sort(reverse=true))[3] ) }}
        #
        # Above avg
      - name: electricity_price_sannesholma_2181_above_avg_price
        unique_id: electricity_price_sannesholma_2181_above_avg_price
        availability: "{{ is_number(states('sensor.elpris')) }}"
        delay_on:
          seconds: 5
        state: >
          {{ states('sensor.elpris') | float('naan') > state_attr('sensor.elpris', 'average') }}
#          {{ states('sensor.electricity_price_sannesholma_2181') | float('naan') > state_attr('sensor.electricity_price_sannesholma_2181', 'avg_price') }}
      #
      # Above low price input
      - name: electricity_price_sannesholma_2181_input_low
        unique_id: electricity_price_sannesholma_2181_input_low
        availability: "{{ is_number(states('input_number.electricity_price_sannesholma_2181_input_low')) }}"
        delay_on:
          seconds: 5
        state: >
          {{ states('input_number.electricity_price_sannesholma_2181_input_low') | float('naan') < states('sensor.elpris') | float('naan') }}
#
#
#
sensor:
  - platform: average
    name: elpris_totalt_medel
    unique_id: elpris_totalt_medel
    start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
    entities:
      - sensor.elpris_totalt_sek
    #
  - platform: average
    name: elpris_tibber_medel
    unique_id: elpris_tibber_medel
    start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
    entities:
      - sensor.electricity_price_sannesholma_2181