template:
  - sensor:
    ### Mikaels rum
    - name: mikaels_rum_ps
      unique_id: mikaels_rum_ps
      device_class: humidity
      availability: "{{ is_number(states('sensor.mikaels_rum_temperature')) }}"
      state: "{{ 288.68 * ( 1.098 + states('sensor.mikaels_rum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
    #
    - name: mikaels_rum_vs
      unique_id: mikaels_rum_vs
      device_class: humidity
      availability: "{{ is_number(states('sensor.mikaels_rum_ps')) and is_number(states('sensor.mikaels_rum_temperature')) }}"
      state: "{{ states('sensor.mikaels_rum_ps') | float(0.0) / ( 461.4 * ( states('sensor.mikaels_rum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
    #
    - name: mikaels_rum_v
      unique_id: mikaels_rum_v
      device_class: humidity
      availability: "{{ is_number(states('sensor.mikaels_rum_vs')) and is_number(states('sensor.mikaels_rum_humidity')) }}"
      state: "{{ ( states('sensor.mikaels_rum_vs') | float(0.0) * ( states('sensor.mikaels_rum_humidity') | float(0.0) / 100 ) ) | round(2) }}"

      ### Snickarboa
    - name: snickarboa_ps
      unique_id: snickarboa_ps
      #friendly_name: "Ånghalt snickarboa ps"
      device_class: "humidity"
      state: "{{ 288.68 * ( 1.098 + states('sensor.snickarboa_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
    - name: snickarboa_vs
      unique_id: snickarboa_vs
      #friendly_name: "Ånghalt snickarboa vs"
      device_class: "humidity"
      state: "{{ states('sensor.snickarboa_ps') | float(0.0) / ( 461.4 * ( states('sensor.snickarboa_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
    - name: snickarboa_v
      unique_id: snickarboa_v
      #  friendly_name: "Ånghalt snickarboa v"
      unit_of_measurement: "g/m3"
      device_class: "humidity"
      state: "{{ ( states('sensor.snickarboa_vs') | float(0.0) * ( states('sensor.snickarboa_humidity') | float(0.0) / 100 ) ) | round(2) }}"
#

sensor:
  - platform: template
    sensors:
      ### Indoor
      indoor_ps:
        friendly_name: "Ånghalt inomhus ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.netatmo_sannesholma_weather_station_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      indoor_vs:
        friendly_name: "Ånghalt inomhus vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.indoor_ps') | float(0.0) / ( 461.4 * ( states('sensor.netatmo_sannesholma_weather_station_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      indoor_v:
        friendly_name: "Ånghalt inomhus v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.indoor_vs') | float(0.0) * ( states('sensor.netatmo_sannesholma_weather_station_humidity') | float(0.0) / 100 ) ) | round(2) }}"
      #
      ### Utomhus
      utomhus_ps:
        friendly_name: "Ånghalt utomhus ps"
        device_class: "humidity"
        value_template: >
          {% if states('sensor.netatmo_sannesholma_weather_station_utomhus_entre_temperature') | float(0.0) >= 0.0 %}
          {{ 288.68 * ( 1.098 + states('sensor.netatmo_sannesholma_weather_station_utomhus_entre_temperature') | float(0.0) / 100 ) ** 8.02 }}
          {% else %}
          {{ 4.689 * ( 1.486 + states('sensor.netatmo_sannesholma_weather_station_utomhus_entre_temperature') | float(0.0) / 100 ) ** 12.3 }}
          {% endif %}
      #
      utomhus_vs:
        friendly_name: "Ånghalt utomhus vs"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ states('sensor.utomhus_ps') | float(0.0) / ( 461.4 * ( states('sensor.netatmo_sannesholma_weather_station_utomhus_entre_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      utomhus_v:
        friendly_name: "Ånghalt utomhus v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.utomhus_vs') | float(0.0) * ( states('sensor.netatmo_sannesholma_weather_station_utomhus_entre_humidity') | float(0.0) / 100 ) ) | round(2) }}"
      #
      ### Tvättstuga
      tvattstuga_ps:
        friendly_name: "Ånghalt tvättstuga ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.tvattstuga_temperatur') | float(0.0) / 100 ) ** 8.02 }}"
      #
      tvattstuga_vs:
        friendly_name: "Ånghalt tvättstuga vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.tvattstuga_ps') | float(0.0) / ( 461.4 * ( states('sensor.tvattstuga_temperatur') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      tvattstuga_v:
        friendly_name: "Ånghalt tvättstuga v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.tvattstuga_vs') | float(0.0) * ( states('sensor.tvattstuga_humidity') | float(0.0) / 100 ) ) | round(2) }}"
      #
      ### Sovrum
      sovrum_ps:
        friendly_name: "Ånghalt sovrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.netatmo_rosa_van_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      sovrum_vs:
        friendly_name: "Ånghalt sovrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.sovrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.netatmo_rosa_van_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      sovrum_v:
        friendly_name: "Ånghalt sovrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.sovrum_vs') | float(0.0) * ( states('sensor.netatmo_rosa_van_humidity') | float(0.0) / 100 ) ) | round(2) }}"
      #
      ### Allrum
      allrum_ps:
        friendly_name: "Ånghalt allrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.netatmo_sannesholma_weather_station_allrum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      allrum_vs:
        friendly_name: "Ånghalt allrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.allrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.netatmo_sannesholma_weather_station_allrum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      allrum_v:
        friendly_name: "Ånghalt allrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.allrum_vs') | float(0.0) * ( states('sensor.netatmo_sannesholma_weather_station_allrum_humidity') | float(0.0) / 100 ) ) | round(2) }}"
      ### Badrum
      badrum_ps:
        friendly_name: "Ånghalt badrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.badrum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      badrum_vs:
        friendly_name: "Ånghalt badrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.badrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.badrum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      badrum_v:
        friendly_name: "Ånghalt badrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.badrum_vs') | float(0.0) * ( states('sensor.badrum_humidity') | float(0.0) / 100 ) ) | round(2) }}"
#
      ### Vardagsrum
      vardagsrum_ps:
        friendly_name: "Ånghalt vardagsrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.vardagsrum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      vardagsrum_vs:
        friendly_name: "Ånghalt vardagsrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.vardagsrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.vardagsrum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      vardagsrum_v:
        friendly_name: "Ånghalt vardagsrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.vardagsrum_vs') | float(0.0) * ( states('sensor.vardagsrum_humidity') | float(0.0) / 100 ) ) | round(2) }}"
#
      ### barnrum
      barnrum_ps:
        friendly_name: "Ånghalt barnrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.barnrum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      barnrum_vs:
        friendly_name: "Ånghalt barnrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.barnrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.barnrum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      barnrum_v:
        friendly_name: "Ånghalt barnrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.barnrum_vs') | float(0.0) * ( states('sensor.barnrum_humidity') | float(0.0) / 100 ) ) | round(2) }}"
#
      ### gastrum
      gastrum_ps:
        friendly_name: "Ånghalt gästrum ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.gastrum_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      gastrum_vs:
        friendly_name: "Ånghalt gästrum vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.gastrum_ps') | float(0.0) / ( 461.4 * ( states('sensor.gastrum_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      gastrum_v:
        friendly_name: "Ånghalt gästrum v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.gastrum_vs') | float(0.0) * ( states('sensor.gastrum_humidity') | float(0.0) / 100 ) ) | round(2) }}"
#
      ### kok
      kok_ps:
        friendly_name: "Ånghalt kök ps"
        device_class: "humidity"
        value_template: "{{ 288.68 * ( 1.098 + states('sensor.kok_temperature') | float(0.0) / 100 ) ** 8.02 }}"
      #
      kok_vs:
        friendly_name: "Ånghalt kök vs"
        device_class: "humidity"
        value_template: "{{ states('sensor.kok_ps') | float(0.0) / ( 461.4 * ( states('sensor.kok_temperature') | float(0.0) + 273.2 ) ) * 1000 }}"
      #
      kok_v:
        friendly_name: "Ånghalt kök v"
        unit_of_measurement: "g/m3"
        device_class: "humidity"
        value_template: "{{ ( states('sensor.kok_vs') | float(0.0) * ( states('sensor.kok_humidity') | float(0.0) / 100 ) ) | round(2) }}"

