################# Circadian ##############################################
adaptive_lighting:
  - name: Gästrum
    lights:
      - light.linas_skrivbord
      - light.gastrum_fonster_1
      - light.gastrum_fonster_2
      # Julstjärna
    #  - light.gastrum_fonster
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 10
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
input_boolean:
  gaster:
    name: Gäster
#
light:
  - platform: group
    name: Gästrum grupp
    unique_id: gastrum_grupp
    entities:
    - light.linas_skrivbord
    - light.gastrum_fonster_1
    - light.gastrum_fonster_2
    # Julstjärna
#    - light.gastrum_fonster
#
#
input_number:
  gastrum_light_level:
    name: Ljusstyrka utomhus för belysning gästrum
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
template:
  - binary_sensor:
      #
      # Ljusstyrka
      - name: gastrum_belysning_lightlevel
        unique_id: gastrum_belysning_lightlevel
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.gastrum_light_level') | float }}
      #
      # Belysning styrning
      - name: gastrum_belysning_automation_control
        unique_id: gastrum_belysning_automation_control
        state: >
          {{ ( is_state('binary_sensor.gastrum_belysning_lightlevel', 'on')
            and is_state('input_boolean.sovdags_gastrum', 'off')
            and is_state('input_boolean.sovdags', 'off') )
            or ( is_state('input_boolean.sovdags_gastrum', 'off') 
            and is_state('input_boolean.gaster', 'on') 
            and is_state('binary_sensor.gastrum_belysning_lightlevel', 'on') ) }}
#
automation:
#
  - alias: Gästrum belysning
    id: Gästrum belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.gastrum_belysning_automation_control
      - platform: state
        entity_id:
          - input_boolean.sovdags_gastrum
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.gastrum_belysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.gastrum_belysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
        - light.gastrum_fonster_1
        - light.gastrum_fonster_2
        # Julstjärna
  #      - light.gastrum_fonster
      - delay:
          seconds: 5
      - service: >
          {% if is_state('input_boolean.sovdags_gastrum', 'on') %}
          switch.turn_off
          {% elif is_state('input_boolean.sovdags_gastrum', 'off') %}
          switch.turn_on
          {% endif %}
        entity_id: switch.adaptive_lighting_gastrum
      - condition: state
        entity_id: input_boolean.sovdags_gastrum
        state: 'off'
      - service: light.turn_off
        entity_id: light.linas_skrivbord
          
#
#
  - alias: Gästrum knapp vid säng
    id: Gästrum knapp vid säng
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: sovrum_knapp
          event: 1002
    action:
      - service: input_boolean.toggle
        target:
          entity_id: input_boolean.sovdags_gastrum