binary_sensor:
#
  - platform: template
    sensors:
      gastrum_belysning_lightlevel:
        friendly_name: Gästrum
        delay_off:
          minutes: 30
        value_template: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.fonsterbelysning_light_level') | float }}
      gastrum_belysning_automation_control:
        friendly_name: Gästrum
        value_template: >-
          {{ is_state('binary_sensor.gastrum_belysning_lightlevel', 'on') }}
#
automation:
#
- alias: Gästrum belysning
  trigger:
  - platform: state
    entity_id: binary_sensor.gastrum_belysning_automation_control
  - platform: homeassistant
    event: start
  action:
  - service: >
      {% if is_state('binary_sensor.gastrum_belysning_automation_control', 'on') %}
      light.turn_on
      {% elif is_state('binary_sensor.gastrum_belysning_automation_control', 'off') %}
      light.turn_off
      {% endif %}
    entity_id:
    - light.gastrum_fonster