################# Circadian ##############################################
adaptive_lighting:
  - name: Hall
    lights:
      - light.hall
      - light.hall_byra
      - light.vardagsrum_tak
      - light.vardagsrum_bord
    prefer_rgb_color: false
    transition: 30
    initial_transition: 2
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
input_number:
#
  hall_light_level:
    name: Ljusstyrka hall för belysning
    min: 0
    max: 100
    step: 1
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
template:
  - trigger:
      - platform: state
        to: 'on'
        from: 'off'
        entity_id: binary_sensor.entre_dorrbrytare
    binary_sensor:
      - name: Hall dörrtrigger
        unique_id: Hall dörrtrigger
        auto_off: 30
        state: "true"
#
  -  binary_sensor:
      ### Närvaro
      - name: hall_presence
        unique_id: hall_presence
        device_class: motion
        delay_off:
          minutes: 10
        state: >
          {{ is_state('binary_sensor.hall_hue_motion_sensor_motion', 'on')
            or is_state('binary_sensor.hall_dorrtrigger', 'on') }}
      #
      ### Närvarostyrd belysning
      - name: hall_presence_light_automation_control
        unique_id: hall_presence_light_automation_control
        state: >
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on')
            or is_state('binary_sensor.hall_presence', 'on') )
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('binary_sensor.hall_lightlevel', 'off') }}
#
      - name: hall_lightlevel
        unique_id: hall_lightlevel
        device_class: light
        availability: "{{ is_number(states('sensor.hall_hue_motion_sensor_light_level')) and is_number(states('input_number.hall_light_level')) }}"
        state: >
          {{ ( states('sensor.hall_hue_motion_sensor_light_level') | float(0.0) > states('input_number.hall_light_level') | float(0.0)
            and is_state('light.hall', 'off') ) 
            or ( is_state('binary_sensor.hall_lightlevel', 'on')
            and is_state('light.hall', 'on') ) }}
#
automation:
  #
  - alias: Hall takbelysning
    id: Hall takbelysning
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_presence_light_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.hall_presence_light_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.hall_presence_light_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.hall
  #
#
