################# Circadian ##############################################
adaptive_lighting:
  - name: Hall
    lights:
      - light.hall
      - light.hall_byra
      - light.vardagsrum_tak
      - light.vardagsrum_bord
    prefer_rgb_color: false
    transition: 30
    initial_transition: 2
    interval: 90
    min_brightness: 30
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
#
template:
  - trigger:
      - platform: state
        to: 'on'
        from: 'off'
        entity_id: binary_sensor.entre_dorrbrytare
    binary_sensor:
      - name: Hall dörrtrigger
        unique_id: Hall dörrtrigger
        auto_off: 30
        state: "true"
#
binary_sensor:
  #
  - platform: template
    sensors:
      ### Närvaro
      hall_presence:
        device_class: motion
        friendly_name: Hall
        delay_off:
          minutes: 10
        value_template: >-
          {{ is_state('binary_sensor.hall_hue_motion_sensor_motion', 'on')
            or is_state('binary_sensor.hall_dorrtrigger', 'on') }}
      #
      ### Närvarostyrd belysning
      hall_presence_light_automation_control:
        friendly_name: Hall
        value_template: >-
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on')
            or is_state('binary_sensor.hall_presence', 'on') )
            and is_state('input_boolean.film_spelar', 'off') }}
#
#
automation:
  #
  - alias: Hall takbelysning
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_presence_light_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.hall_presence_light_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.hall_presence_light_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.hall
  #
#
