sensor:
### Krisinformation
  - platform: krisinformation
    radius: 20
#
binary_sensor:
  - platform: template
    sensors:
      krisinformation_alert:
        value_template: "{{ is_state('sensor.krisinformation', 'Alert') }}"
#
alert:
#
  krisinformation:
    name: Krisinformation!
    done_message: Faran är över
    entity_id: binary_sensor.krisinformation_alert
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - pushbullet_lina
#
automation:
  - alias: Krisinformation blink
    trigger:
      platform: time_pattern
      minutes: "/5"
    condition:
    - condition: state
      entity_id: binary_sensor.krisinformation_alert
      state: 'on'
    - condition: state
      entity_id: input_boolean.sovdags
      state: 'on'
    action:
    - service: light.turn_on
      entity_id: light.sovrum
      data:
        flash: long
#
  - alias: 'Krisinformation Alert'
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.krisinformation
      to: "Alert"
    action:
      - service: notify.pushbullet
        data_template:
          message: >
            {{states.sensor.krisinformation.attributes.messages[0].Headline}} - {{states.sensor.krisinformation.attributes.messages[0].Message}} {{states.sensor.krisinformation.attributes.messages[0].Web}}
      - service: notify.pushbullet_lina
        data_template:
          message: >
            {{states.sensor.krisinformation.attributes.messages[0].Headline}} - {{states.sensor.krisinformation.attributes.messages[0].Message}} {{states.sensor.krisinformation.attributes.messages[0].Web}}