##################### Brandvarnare #####################################
automation:
- alias: Kontroll av brandvarnare
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 32
      sub_type: 3
      id_string: "b38d00:32"
      values:
        Sensor Status: "Panic"
#  - platform: state
#    entity_id:
#      - binary_sensor.kd101_smoke_detector_b38d00_32
#    to: 'on'
  action:
#  - service: notify.pushbullet
#    data_template:
#      message: "Brandvarnare aktiv"
#      title: "Rök detekterad"
  - service: notify.mobile_app_sm_n975f
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
  - service: notify.mobile_app_sm_g998b
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
#  - service: notify.pushbullet_lina
#    data_template:
#      message: "Brandvarnare aktiv"
#      title: "Rök detekterad"
  - service: persistent_notification.create
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
      #
template:
- trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 32
      sub_type: 3
      id_string: "b38d00:32"
      values:
        Sensor Status: "Panic"
  binary_sensor:
    - name: Brandvarnare
      auto_off: 300
      state: "true"
alert:
  fire:
    name: Brandvarnare utlöst, risk för brand!
    done_message: Brandvarnare är återställd
    entity_id: binary_sensor.brandvarnare
    state: 'on'
    repeat: 5
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_sm_g998b
      - persistent_notification
#
#
  kok_lackagevakt:
    name: Läckagevakt i kök
    title: Läckagevakt i kök utlöst!
    message: Kontrollera under diskho
    done_message: Läckagevakt är återställd
    entity_id: binary_sensor.kok_lackagevakt
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_sm_g998b
      - persistent_notification
#
  heatpump_sumalarm:
    name: Sumalarm Värmepump
    title: Sumalarm Värmepump
    message: Sumalart utlöst
    done_message: Sumalarm återställt
    entity_id: binary_sensor.heatpump_sumalarm
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_sm_g998b
      - persistent_notification