##################### Brandvarnare #####################################
automation:
- alias: Kontroll av brandvarnare
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 32
      sub_type: 3
      id_string: "b38d00:32"
      values:
        Sensor Status: "Panic"
#
  action:
  - service: notify.mobile_app_mikael_iphone
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
  - service: notify.mobile_app_sm_g998b
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
  - service: persistent_notification.create
    data_template:
      message: "Brandvarnare aktiv"
      title: "Rök detekterad"
      #
template:
  - trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 32
        sub_type: 3
        id_string: "b38d00:32"
        values:
          Sensor Status: "Panic"
    binary_sensor:
      - name: Brandvarnare
        auto_off: 300
        state: "true"
#
input_boolean:
  larmtest:
    name: Larmtest
#
alert:
  fire:
    name: Brandvarnare utlöst, risk för brand!
    done_message: Brandvarnare är återställd
    entity_id: binary_sensor.brandvarnare
    state: 'on'
    repeat: 5
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_mikael_iphone
      - mobile_app_sm_g998b
      - persistent_notification
    data:
      push:
        sound:
          critical: 1
          volume: 1.0
#
#
  kok_lackagevakt:
    name: Läckagevakt i kök
    title: Läckagevakt i kök utlöst!
    message: Kontrollera under diskho
    done_message: Läckagevakt är återställd
    entity_id: binary_sensor.kok_lackagevakt
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_mikael_iphone
      - persistent_notification
    data:
      push:
        sound:
          critical: 1
          volume: 1.0
#
  heatpump_sumalarm:
    name: Sumalarm Värmepump
    title: Sumalarm Värmepump
    message: Sumalart utlöst
    done_message: Sumalarm återställt
    entity_id: binary_sensor.heatpump_sumalarm
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_mikael_iphone
#      - mobile_app_sm_g998b
      - persistent_notification
#
  snickarboa_temperature_low:
    name: Låg temperatur i snickarboa
    title: Låg temperatur i snickarboa
    message: Risk för frysskador
    done_message: Temperaturen är bra igen
    entity_id: binary_sensor.snickarboa_tempterature_low
    state: 'on'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_sm_g998b
      - mobile_app_mikael_iphone
      - persistent_notification
#
  snickarboa_frys_temperature_low:
    name: Hög temperatur frys i snickarboa
    title: Hög temperatur frys i snickarboa
    message: Risk för att det tinar
    done_message: Temperaturen är bra igen
    entity_id: binary_sensor.snickarboa_frys_tempterature_low
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_n975f
      - mobile_app_sm_g998b
      - mobile_app_mikael_iphone
      - persistent_notification
#
  test:
    name: Hög temperatur frys i snickarboa
    title: Hög temperatur frys i snickarboa
    message: Risk för att det tinar
    done_message: Temperaturen är bra igen
    entity_id: input_boolean.larmtest
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_mikael_iphone
    data:
      push:
        sound:
          critical: 1
          volume: 1.0