################# Circadian ##############################################
adaptive_lighting:
  - name: Mikaels rum
    lights:
      - light.mikaels_dator_hue_play_1
      - light.mikaels_dator_hue_play_2
      - light.kontor_fonster
      - light.mikaels_rum_skrivbord
      - light.mikaels_rum_tak
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2100
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
    #sunrise_time: "07:00:00" # override the sunrise time
    #    sunrise_offset:
    #    sunset_time: "20:00:00"
    #    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: true
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: false

  - name: Mikaels rum ljusslinga
    lights:
      - light.mikaels_rum_ljusslinga
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 70
    max_brightness: 100
    min_color_temp: 2100
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
#    max_sunrise_time: 07:00:00
    #sunrise_time: "07:00:00" # override the sunrise time
    #    sunrise_offset:
    #    sunset_time: "20:00:00"
    #    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: true
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: false
#
light:
  - platform: group
    name: Mikaels rum
    unique_id: mikaels_rum
    entities:
      - light.mikaels_dator_hue_play_1
      - light.mikaels_dator_hue_play_2
      - light.kontor_fonster
      - light.mikaels_rum_skrivbord
      - light.mikaels_rum_ljusslinga
      - light.mikaels_rum_tak
#
template:
#
  - binary_sensor:
  #
      - name: mikaels_rum_belysning_lightlevel
        unique_id: mikaels_rum_belysning_lightlevel
        delay_off:
          minutes: 5
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.fonsterbelysning_light_level') | float }}
      #
      - name: mikaels_rum_belysning_automation_control
        unique_id: mikaels_rum_belysning_automation_control
        state: >
          {{ is_state('binary_sensor.mikaels_rum_belysning_lightlevel', 'on') }}
      #
      - name: mikaels_rum_närvaro
        unique_id: mikaels_rum_närvaro
        delay_off:
          minutes: 10
        state: >
          {{ is_state('binary_sensor.mikaels_rum_rorelsesensor', 'on') }}
      #
      - name: mikaels_rum_belysning_av
        unique_id: mikaels_rum_belysning_av
        delay_off:
          minutes: 60
        state: >
          {{ is_state('binary_sensor.mikaels_rum_rorelsesensor', 'on') }}
#
automation:
  #
  - alias: Mikaels rum belysning
    id: Mikaels rum belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.mikaels_rum_belysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.mikaels_rum_belysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.mikaels_rum_belysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.kontor_fonster
#
  - alias: Mikaels rum belysning av
    id: Mikaels rum belysning av
    trigger:
      - platform: state
        entity_id: binary_sensor.mikaels_rum_belysning_av
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.mikaels_rum_hue
