################# Circadian ##############################################
adaptive_lighting:
  #
  - name: Snickarboa
    lights:
      - light.snickarboa_arbetsbank
      - light.snickarboa_spotlights
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2200
    max_color_temp: 4000
    sleep_brightness: 1
    take_over_control: true
    separate_turn_on_commands: true
#
#
#generic_hygrostat:
#  - name: Snickarboa
#    humidifier: input_boolean.avfuktare
#    target_sensor: sensor.snickarboa_humidity
#    device_class: "dehumidifier"
#    max_humidity: 75
#
climate:
  - platform: generic_thermostat
    name: Snickarboa
    unique_id: Snickarboa
    cold_tolerance: 0.5
    hot_tolerance: 1
    precision: 0.1
    heater: switch.snickarboa_heater
    target_sensor: sensor.snickarboa_temperature
    min_temp: 0
    activity_temp: 7
#
#
binary_sensor:
  - platform: trend
    sensors:
      snickarboa_frys:
        invert: "true"
        friendly_name: Snickarboa frys
        entity_id: sensor.snickarboa_frys_temperature
#
#
sensor:
  - platform: integration
    source: sensor.avfuktare_power
    name: Avfuktare_consumption
    unique_id: Avfuktare_consumption
    unit_prefix: k
    round: 2
    method: left
    #
  #
  - platform: history_stats
    unique_id: snickarboa_heater_today
    name: snickarboa_heater_today
    entity_id: switch.snickarboa_heater
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now().replace(microsecond=0) }}"
  #
  - platform: history_stats
    unique_id: snickarboa_frys_time_today
    name: snickarboa_frys_time_today
    entity_id: binary_sensor.snickarboa_frys
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now().replace(microsecond=0) }}"
#
utility_meter:
  ######################## Avfuktare #########################################
  #
  ###################
  ### Förbrukning ###
  ###################
  avfuktare_timme:
    unique_id: avfuktare_timme
    source: sensor.avfuktare_consumption
    cycle: hourly
  avfuktare_dag:
    unique_id: avfuktare_dag
    source: sensor.avfuktare_consumption
    cycle: daily
  avfuktare_vecka:
    unique_id: avfuktare_vecka
    source: sensor.avfuktare_consumption
    cycle: weekly
  avfuktare_manad:
    unique_id: avfuktare_manad
    source: sensor.avfuktare_consumption
    cycle: monthly
  avfuktare_ar:
    unique_id: avfuktare_ar
    source: sensor.avfuktare_consumption
    cycle: yearly
  ################
  ### Kostnad ####
  ################
  avfuktare_dag_kostnad:
    unique_id: avfuktare_dag_kostnad
    source: sensor.avfuktare_timme_kostnad
    cycle: daily
  avfuktare_manad_kostnad:
    unique_id: avfuktare_manad_kostnad
    source: sensor.avfuktare_timme_kostnad
    cycle: monthly
  avfuktare_ar_kostnad:
    unique_id: avfuktare_ar_kostnad
    source: sensor.avfuktare_timme_kostnad
    cycle: yearly
  #
  ########### Värmare ########################################################
  #
  ###################
  ### Förbrukning ###
  ###################
  snickarboa_heater_timme:
    unique_id: snickarboa_heater_timme
    source: sensor.snickarboa_heater_dag
    cycle: hourly
  snickarboa_heater_vecka:
    unique_id: snickarboa_heater_vecka
    source: sensor.snickarboa_heater_dag
    cycle: weekly
  snickarboa_heater_manad:
    unique_id: snickarboa_heater_manad
    source: sensor.snickarboa_heater_dag
    cycle: monthly
  snickarboa_heater_ar:
    unique_id: snickarboa_heater_ar
    source: sensor.snickarboa_heater_dag
    cycle: yearly
  #
  ################
  ### Kostnad ####
  ################
  #
  snickarboa_heater_dag_kostnad:
    unique_id: snickarboa_heater_dag_kostnad
    source: sensor.snickarboa_heater_timme_kostnad
    cycle: daily
  snickarboa_heater_manad_kostnad:
    unique_id: snickarboa_heater_manad_kostnad
    source: sensor.snickarboa_heater_timme_kostnad
    cycle: monthly
  snickarboa_heater_ar_kostnad:
    unique_id: snickarboa_heater_ar_kostnad
    source: sensor.snickarboa_heater_timme_kostnad
    cycle: yearly
  #
  #######################################
  ### Förbrukning från sol eller nät ####
  #######################################
  snickarboa_heater_timme_from:
    unique_id: snickarboa_heater_timme_from
    source: sensor.snickarboa_heater_dag
    cycle: hourly
    tariffs:
      - grid
      - solar
  snickarboa_heater_dag_from:
    unique_id: snickarboa_heater_dag_from
    source: sensor.snickarboa_heater_dag
    cycle: hourly
    tariffs:
      - grid
      - solar
  snickarboa_heater_manad_from:
    unique_id: snickarboa_heater_manad_from
    source: sensor.snickarboa_heater_dag
    cycle: monthly
    tariffs:
      - grid
      - solar
  #
  ########### Frys ########################################################
  #
  ###################
  ### Förbrukning ###
  ###################
  snickarboa_frys_timme:
    unique_id: snickarboa_frys_timme
    source: sensor.snickarboa_frys_dag
    cycle: hourly
  snickarboa_frys_vecka:
    unique_id: snickarboa_frys_vecka
    source: sensor.snickarboa_frys_dag
    cycle: weekly
  snickarboa_frys_manad:
    unique_id: snickarboa_frys_manad
    source: sensor.snickarboa_frys_dag
    cycle: monthly
  snickarboa_frys_ar:
    unique_id: snickarboa_frys_ar
    source: sensor.snickarboa_frys_dag
    cycle: yearly
  #
  ################
  ### Kostnad ####
  ################
  #
  snickarboa_frys_dag_kostnad:
    unique_id: snickarboa_frys_dag_kostnad
    source: sensor.snickarboa_frys_timme_kostnad
    cycle: daily
  snickarboa_frys_manad_kostnad:
    unique_id: snickarboa_frys_manad_kostnad
    source: sensor.snickarboa_frys_timme_kostnad
    cycle: monthly
  snickarboa_frys_ar_kostnad:
    unique_id: snickarboa_frys_ar_kostnad
    source: sensor.snickarboa_frys_timme_kostnad
    cycle: yearly
  #
  ################
  ### Besparing ##
  ################
  #
  snickarboa_frys_dag_from_solar_savings:
    unique_id: snickarboa_frys_dag_from_solar_savings
    source: sensor.snickarboa_frys_timme_from_solar_savings
    cycle: daily
  snickarboa_frys_manad_from_solar_savings:
    unique_id: snickarboa_frys_manad_from_solar_savings
    source: sensor.snickarboa_frys_timme_from_solar_savings
    cycle: monthly
  snickarboa_frys_ar_from_solar_savings:
    unique_id: snickarboa_frys_ar_from_solar_savings
    source: sensor.snickarboa_frys_timme_from_solar_savings
    cycle: yearly
  #
  #######################################
  ### Förbrukning från sol eller nät ####
  #######################################
  snickarboa_frys_timme_from:
    unique_id: snickarboa_frys_timme_from
    source: sensor.snickarboa_frys_dag
    cycle: hourly
    tariffs:
      - grid
      - solar
  snickarboa_frys_dag_from:
    unique_id: snickarboa_frys_dag_from
    source: sensor.snickarboa_frys_dag
    cycle: hourly
    tariffs:
      - grid
      - solar
  snickarboa_frys_manad_from:
    unique_id: snickarboa_frys_manad_from
    source: sensor.snickarboa_frys_dag
    cycle: monthly
    tariffs:
      - grid
      - solar
#
input_number:
  snickarboa_light_level:
    name: Ljusstyrka snickarboa för belysning
    min: 0
    max: 1000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
  # Låg temperatur i snickarboa
  snickarboa_temperature_low:
    name: Snickarboa låg temperatur
    min: 0
    max: 7
    step: 1
    unit_of_measurement: °C
  # Låg temperatur frys i snickarboa
  snickarboa_frys_temperature_low:
    name: Snickarboa frys låg temperatur
    min: -20
    max: -14
    step: 1
    unit_of_measurement: °C
#
#
template:
  - binary_sensor:
      #
      #
      - name: snickarboa_heater
        unique_id: snickarboa_heater
        state: >
          {{ is_state('binary_sensor.heatpump_emhass', 'on') }}
      #
      ### Light level
      - name: snickarboa_lightlevel
        unique_id: snickarboa_lightlevel
        device_class: light
        delay_on:
          minutes: 10
        state: >
          {{ states('sensor.snickarboa_hue_motion_sensor_light_level') | float > states('input_number.snickarboa_light_level') | float }}
      #
      # Belysning närvaro
      - name: snickarboa_presence_light_automation_control
        unique_id: snickarboa_presence_light_automation_control
        state: >
          {{ is_state('binary_sensor.snickarboa_presence', 'on')
            and is_state('binary_sensor.snickarboa_lightlevel', 'off') }}
      #
      ### Närvaro
      - name: snickarboa_presence
        unique_id: snickarboa_presence
        device_class: motion
        delay_off:
          minutes: 5
        state: >
          {{ is_state('binary_sensor.snickarboa_hue_motion_sensor_motion', 'on')
          or is_state('binary_sensor.snickarboa_dorrtrigger', 'on') }}
      #
      ### Låg tempteratur
      - name: snickarboa_tempterature_low
        unique_id: snickarboa_tempterature_low
        delay_on:
          minutes: 1
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.snickarboa_temperature') | float(0.0) < states('input_number.snickarboa_temperature_low') | float(0.0) }}
      #
      ### Låg temperatur frys
      - name: snickarboa_frys_tempterature_low
        unique_id: snickarboa_frys_tempterature_low
        delay_on:
          minutes: 1
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.snickarboa_frys_temperature') | float(0.0) > states('input_number.snickarboa_frys_temperature_low') | float(0.0) }}
  #
  - trigger:
      - platform: state
        to: "on"
        from: "off"
        entity_id: binary_sensor.snickarboa_dorrbrytare
    binary_sensor:
      - name: Snickarboa dörrtrigger
        unique_id: Snickarboa dörrtrigger
        auto_off: 30
        state: "true"
  #
  - sensor:
      #
      ### Förbrukning uppvärmning
      - name: snickarboa_heater_dag
        unique_id: snickarboa_heater_dag
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        availability: "{{ is_number(states('sensor.snickarboa_heater_today')) }}"
        state: >
          {{ ( 600.0 * states('sensor.snickarboa_heater_today') | float('nan') / 1000.0 ) | round(3) }}
      #
      #### Förbrukning frys
      - name: snickarboa_frys_dag
        unique_id: snickarboa_frys_dag
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        availability: "{{ is_number(states('sensor.snickarboa_frys_time_today')) }}"
        state: >
          {{ ( 75.0 * states('sensor.snickarboa_frys_time_today') | float('nan') / 1000.0 ) | round(3) }}
      #
      ### Kostnad frys
      - name: snickarboa_frys_timme_kostnad
        unique_id: snickarboa_frys_timme_kostnad
        unit_of_measurement: "SEK"
        device_class: monetary
        availability: "{{ is_number(states('sensor.snickarboa_frys_timme_from_grid')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.snickarboa_frys_timme_from_grid') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"
      #
      ### Besparing frys
      - name: snickarboa_frys_timme_from_solar_savings
        unique_id: snickarboa_frys_timme_from_solar_savings
        unit_of_measurement: "SEK"
        device_class: monetary
        availability: "{{ is_number(states('sensor.snickarboa_frys_timme_from_solar')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.snickarboa_frys_timme_from_solar') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"
      #
      ### Avfuktare kostnad
      - name: avfuktare_timme_kostnad
        unique_id: avfuktare_timme_kostnad
        unit_of_measurement: "SEK"
        availability: "{{ is_number(states('sensor.avfuktare_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.avfuktare_timme') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"
        #
        ### Värmare kostnad
      - name: snickarboa_heater_timme_kostnad
        unique_id: snickarboa_heater_timme_kostnad
        unit_of_measurement: "SEK"
        availability: "{{ is_number(states('sensor.snickarboa_heater_timme')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.snickarboa_heater_timme') | float(0.0) * states('sensor.elpris_totalt_sek') | float(0.0) ) | round(3) }}"
#
automation:
  #
  - alias: Avfuktare
    id: Avfuktare
    trigger:
      - platform: state
        entity_id: binary_sensor.avfuktare
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.avfuktare', 'on') %}
          switch.turn_on
          {% elif is_state('binary_sensor.avfuktare', 'off') %}
          switch.turn_off
          {% endif %}
        entity_id:
          - switch.avfuktare
  #
  - alias: Snickarboa värmare
    id: Snickarboa värmare
    trigger:
      - platform: state
        entity_id: binary_sensor.snickarboa_heater
      - platform: homeassistant
        event: start
    action:
      - choose:
          #
          - conditions:
              - condition: state
                state: "on"
                entity_id: binary_sensor.snickarboa_heater
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: climate.snickarboa
                data:
                  hvac_mode: "heat"
          #
          - conditions:
              - condition: state
                state: "off"
                entity_id: binary_sensor.snickarboa_heater
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: climate.snickarboa
                data:
                  hvac_mode: "off"
  #
  #
  - alias: Snickarboa belysning
    id: Snickarboa belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.snickarboa_presence_light_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.snickarboa_presence_light_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.snickarboa_presence_light_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.snickarboa_arbetsbank
          - light.snickarboa_spotlights
  #
  - alias: Snickarboa frys energikalla
    id: Snickarboa frys energikalla
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.power_from_grid
      - platform: homeassistant
        event: start
    action:
      - choose:
          #
          - conditions:
              - condition: state
                state: "on"
                entity_id: binary_sensor.power_from_grid
            sequence:
              - service: select.select_option
                target:
                  entity_id:
                    - select.snickarboa_frys_timme_from
                    - select.snickarboa_frys_dag_from
                    - select.snickarboa_frys_manad_from
                data:
                  option: "grid"
          #
          #
          - conditions:
              - condition: state
                state: "off"
                entity_id: binary_sensor.power_from_grid
            sequence:
              - service: select.select_option
                target:
                  entity_id: 
                    - select.snickarboa_frys_timme_from
                    - select.snickarboa_frys_dag_from
                    - select.snickarboa_frys_manad_from
                data:
                  option: "solar"