#waste_collection_schedule:
#  sources:
#    - name: ssam_se
#      args:
#        street_address: Sännesholma 2181, Hallaryd


automation:
############## Sopor ######################################################
  #
  #
#
  - alias: ssam_sophatmning_fni1
    id: ssam_sophatmning_fni1
    trigger:
      platform: state
      entity_id: sensor.ssam_sophatmning_fni1
      attribute: days_from_today
      to: 1
    action:
      - service: persistent_notification.create
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 1"
      - service: notify.mobile_app_mikael_iphone
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 1"
      - service: notify.mobile_app_lina_iphone
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 1"
#
#
  - alias: ssam_sophatmning_fni2
    id: ssam_sophatmning_fni2
    trigger:
      platform: state
      entity_id: sensor.ssam_sophatmning_fni2
      attribute: days_from_today
      to: 1
    action:
      - service: persistent_notification.create
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 2"
      - service: notify.mobile_app_mikael_iphone
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 2"
      - service: notify.mobile_app_lina_iphone
        data_template:
          message: "Sophämtning"
          title: "Imorgon tömts kärl 2"