#
input_boolean:
  sovdags:
    name: Sovdags
    icon: mdi:sleep
#
  sovdags_gastrum:
    name: Sovdags gästrum
    icon: mdi:sleep
#
automation:
  #######################################################################################
  ################ Sovdags ############################
  - alias: Sovdags
    trigger:
      platform: state
      entity_id: input_boolean.sovdags
    action:
      - choose:
      #
        - conditions:
            - condition: state
              entity_id: input_boolean.sovdags
              state: 'on'
          sequence:
            - delay:
                seconds: 10
            - service: light.turn_off
              data:
                entity_id:
                  # Sovrum
                  #- light.sovrum
                  # Mikaels rum
                  - light.mikaels_rum_tak
                  - light.mikaels_rum_hue_play
                  - light.mikaels_rum_ljusslinga
                  - light.mikaels_rum_skrivbord
                  # Gästrum
                  - light.linas_skrivbord
                  # Kimi
                  - light.barnrum_tak_1
            - delay:
                seconds: 5
            - service: switch.turn_on
              data:
                entity_id:
                  - switch.adaptive_lighting_sleep_mode_allrum
                  - switch.adaptive_lighting_sleep_mode_allrum_belysning_filament
                  #
                  - switch.adaptive_lighting_sleep_mode_badrum
                  #
                  - switch.adaptive_lighting_sleep_mode_kok
                  - switch.adaptive_lighting_sleep_mode_kok_fonster
                  #
                  - switch.adaptive_lighting_sleep_mode_sovrum
                  #
                  - switch.adaptive_lighting_sleep_mode_tvattstuga
                  #
                  - switch.adaptive_lighting_sleep_mode_vardagsrum_belysning_filament
                  #
                  - switch.adaptive_lighting_sleep_mode_hall
                  #
        # Sovdags av
        - conditions:
            - condition: state
              entity_id: input_boolean.sovdags
              state: 'off'
          sequence:
            - service: switch.turn_off
              data:
                entity_id:
                  - switch.adaptive_lighting_sleep_mode_allrum
                  - switch.adaptive_lighting_sleep_mode_allrum_belysning_filament
                  #
                  - switch.adaptive_lighting_sleep_mode_badrum
                  #
      #            - switch.adaptive_lighting_sleep_mode_barnrum
                  #
                  - switch.adaptive_lighting_sleep_mode_kok
                  - switch.adaptive_lighting_sleep_mode_kok_fonster
                  #
                  - switch.adaptive_lighting_sleep_mode_sovrum
                  #
                  - switch.adaptive_lighting_sleep_mode_tvattstuga
                  #
                  - switch.adaptive_lighting_sleep_mode_vardagsrum_belysning_filament
                  #
                  - switch.adaptive_lighting_sleep_mode_hall
                  #
      #            - switch.adaptive_lighting_sleep_mode_gastrum
            #
            - service: switch.turn_on
              data:
                entity_id:
                  - switch.adaptive_lighting_sovrum
      #