################# Circadian ##############################################
adaptive_lighting:
  - name: Sovrum
    lights:
      - light.walk_in_closet
#      - light.sovrum_fonster
      - light.sovrum_byra
      - light.sovrum_sang_mikael
      - light.sovrum_sang_lina
    transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
light:
  - platform: group
    name: Sovrum grupp
    unique_id: Sovrum grupp
    entities:
      - light.sovrum
      - light.walk_in_closet
#
input_number:
  sovrum_light_level:
    name: Ljusstyrka utomhus för belysning sovrum
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
#
template:
  - binary_sensor:
      - name: sovrum_belysning_lightlevel
        unique_id: sovrum_belysning_lightlevel
        device_class: light
        delay_off:
          minutes: 10
        state: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.sovrum_light_level') | float }}
      #
      - name: sovrum_belysning_automation_control
        unique_id: sovrum_belysning_automation_control
        state: >-
          {{ is_state('binary_sensor.sovrum_belysning_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
#
automation:
  #
  - alias: Sovrum belysning
    id: Sovrum belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.sovrum_belysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.sovrum_belysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.sovrum_belysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
#          - light.sovrum_fonster
          - light.sovrum_byra
          - light.sovrum_sang_lina
          - light.sovrum_sang_mikael
  #
  - alias: Sovrum Säng Mikael Knapp
    id: Sovrum Säng Mikael Knapp
    trigger:
      - platform: device
        domain: mqtt
        device_id: d804ff674d445d8a0704fc6dc3634837
        type: action
        subtype: single
      - platform: device
        domain: mqtt
        device_id: d804ff674d445d8a0704fc6dc3634837
        type: action
        subtype: double
      - platform: device
        domain: mqtt
        device_id: d804ff674d445d8a0704fc6dc3634837
        type: action
        subtype: hold
    action:
      - choose:
          # Short press
          - conditions:
              - condition: template
                value_template: '{{ trigger.payload == "single" }}'
            sequence:
              - service: input_boolean.toggle
                target:
                  entity_id: input_boolean.sovdags
          #
          # Double press
          - conditions:
              - condition: template
                value_template: '{{ trigger.payload == "double" }}'
            sequence:
              - service: light.toggle
                target:
                  entity_id: light.sovrum_sang_mikael
          #
          # Long press
          - conditions:
              - condition: template
                value_template: '{{ trigger.payload == "hold" }}'
            sequence:
              - service: light.turn_off
                entity_id: light.sovrum
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sovrum
#
#
# https://community.home-assistant.io/t/automation-with-templates-and-choose-action/218338
