################# Circadian ##############################################
adaptive_lighting:
  - name: Sovrum
    lights:
      - light.walk_in_closet
      - light.sovrum_fonster
      - light.sovrum_byra
      - light.sovrum_sang_mikael
      - light.sovrum_sang_lina
    transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 10
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_rgb_or_color_temp: rgb_color
    sleep_rgb_color: [255, 161, 40]
    take_over_control: true
    detect_non_ha_changes: true
#
light:
  - platform: group
    name: Sovrum grupp
    unique_id: Sovrum grupp
    entities:
      - light.sovrum
      - light.walk_in_closet
#
input_number:
  sovrum_light_level:
    name: Ljusstyrka utomhus för belysning sovrum
    min: 0
    max: 1000
    step: 50
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
#sensor:
#  - platform: template
#    sensors:
      ############# Temperatur #########################
#      netatmo_sovrum_temperature:
#        unit_of_measurement: "°C"
#        friendly_name: Sovrum termostat temperatur
#        value_template: "{{ state_attr('climate.netatmo_sovrum', 'current_temperature') }}"
#
template:
  - binary_sensor:
      - name: sovrum_belysning_lightlevel
        unique_id: sovrum_belysning_lightlevel
        device_class: light
        delay_off:
          minutes: 30
        state: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.sovrum_light_level') | float }}
      #
      - name: sovrum_belysning_automation_control
        unique_id: sovrum_belysning_automation_control
        state: >-
          {{ is_state('binary_sensor.sovrum_belysning_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
#
automation:
  #
  - alias: Sovrum belysning
    id: Sovrum belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.sovrum_belysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.sovrum_belysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.sovrum_belysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.sovrum_fonster
          - light.sovrum_byra
#
  - alias: Sovrum Säng Mikael Knapp
    id: Sovrum Säng Mikael Knapp
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: sovrum_sang_mikael_smart_switch
    action:
      - choose:
        # Short press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1002 }}'
          sequence:
            - service: input_boolean.toggle
              target:
                entity_id: input_boolean.sovdags
#
        # Double press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1004 }}'
          sequence:
            - service: light.toggle
              target:
                entity_id: light.sovrum_sang_mikael
#
        # Long press
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.event == 1001 }}'
          sequence:
            - service: switch.toggle
              entity_id: switch.adaptive_lighting_sleep_mode_sovrum

#  - alias: Sovrum Säng Mikael Knapp 2 klick
#    trigger:
#      - platform: event
#        event_type: deconz_event
#        event_data:
#          id: sovrum_sang_mikael_smart_switch
#          event: 1004
#    action:
#      - service: light.toggle
#        target:
#          entity_id: light.sovrum_sang_mikael

# https://community.home-assistant.io/t/automation-with-templates-and-choose-action/218338