sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
#        arg: /home
      - type: memory_use_percent
      - type: load_1m
      - type: processor_use
      - type: last_boot