#
automation:
##############  ############################################################################################################
##############  ###################################################
  ##############  ####################################################
#  - alias: Climate away
#    trigger:
#      platform: state
#      entity_id: binary_sensor.climate_away
#      to: 'on'
#    action:
#    - service: climate.set_preset_mode
#      data:
#        entity_id:
#        - climate.netatmo_allrum
#        preset_mode: 'away'
  ##############  ####################################################
  - alias: radiatorer
    id: radiatorer
    trigger:
      - platform: state
        entity_id: binary_sensor.varmegolv_block
      - platform: homeassistant
        event: start
#
    action:
      - choose:
          #
          - conditions:
              - condition: state
                state: 'off'
                entity_id: binary_sensor.varmegolv_block
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id:
                  - climate.netatmo_allrum
                  preset_mode: 'Schedule'
          #
          - conditions:
              - condition: state
                state: 'on'
                entity_id: binary_sensor.varmegolv_block
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id:
                  - climate.netatmo_allrum
                  preset_mode: 'Frost Guard'