utility_meter:
  ###################
  ### Förbrukning ###
  ###################
  torktumlare_dag:
    unique_id: torktumlare_dag
    source: sensor.torktumlare_consumption
    periodically_resetting: false
    cycle: daily
  torktumlare_manad:
    unique_id: torktumlare_manad
    source: sensor.torktumlare_consumption
    periodically_resetting: false
    cycle: monthly
  torktumlare_ar:
    unique_id: torktumlare_ar
    source: sensor.torktumlare_consumption
    periodically_resetting: false
    cycle: yearly
  #
#
#
template:
  - binary_sensor:
# Torktumlare
    - name: torktumlare
      unique_id: torktumlare
      delay_on:
        seconds: 10
      delay_off:
        minutes: 2
      state: >
        {{ states('sensor.torktumlare_power') | float(0.0) > 1 }}
#      icon_template: mdi:tumble-dryer
#
automation:
  - alias: Torktumlare klar
    id: Torktumlare klar
    trigger:
      platform: state
      entity_id: binary_sensor.torktumlare
      from: "on"
      to: "off"
    action:
      - service: persistent_notification.create
        data_template:
          message: "Torktumlare"
          title: "Torktumlaren är klar"
      - service: notify.mobile_app_mikael_iphone
        data_template:
          message: "Torktumlare klar"
          title: "Torktumlaren är klar"
      - service: notify.mobile_app_lina_iphone
        data_template:
          message: "Torktumlare"
          title: "Torktumlaren är klar"
#