################# Circadian ##############################################
adaptive_lighting:
- name: Tvättstuga
  lights:
    - light.tvattstuga_fonster
  prefer_rgb_color: false
  transition: 45
  initial_transition: 0
  interval: 90
  min_brightness: 1
  max_brightness: 35
  sleep_brightness: 2
  take_over_control: true
  detect_non_ha_changes: false
#
template:
  #
  - binary_sensor:
    - name: tvattstuga_belysning_lightlevel
      unique_id: tvattstuga_belysning_lightlevel
      delay_off:
        minutes: 30
      state: >
        {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.fonsterbelysning_light_level') | float }}
#
    - name: tvattstuga_belysning_automation_control
      unique_id: tvattstuga_belysning_automation_control
      state: >
        {{ is_state('binary_sensor.tvattstuga_belysning_lightlevel', 'on') }}
    #
    - name: tvattstuga_kattlucka
      unique_id: tvattstuga_kattlucka
      delay_off:
        seconds: 10
      state: >
        {{ is_state('binary_sensor.tvattstuga_kattlucka_oppning', 'on') }}
#
automation:
  #
  - alias: Tvättstuga belysning
    id: tvattstuga_belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.tvattstuga_belysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.tvattstuga_belysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.tvattstuga_belysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.tvattstuga_fonster
