################# Circadian ##############################################
adaptive_lighting:
  - name: Utomhusbelysning
    lights:
      - light.groventre_dorr
      - light.koksentre_dorr
    prefer_rgb_color: false
    transition: 0
    initial_transition: 0
    interval: 90
    min_brightness: 10
    max_brightness: 90
    min_color_temp: 2400
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
    sunrise_time: "07:00:00" # override the sunrise time
    #    sunrise_offset:
    #    sunset_time:
    #    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: true
  #
  - name: Utomhusbelysning hue
    lights:
      - light.entre_dorr
      - light.snickarboa_entre
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 30
    max_brightness: 100
    min_color_temp: 2400
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
    sunrise_time: "07:00:00" # override the sunrise time
    #    sunrise_offset:
    #    sunset_time:
    #    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: false
#
light:
  - platform: group
    name: Utomhusbelysning grupp
    unique_id: utomhusbelysning_grupp
    entities:
      - light.entre_dorr
      - light.groventre_dorr
      - light.koksentre_dorr
      - light.entre_ljusslinga
      - light.koksentre_ljusslinga
      - light.snickarboa_entre
#
input_number:
  utomhusbelysning_light_level:
    name: Ljusstyrka för utomhusbelysning
    min: 0
    max: 400
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
binary_sensor:
  - platform: template
    sensors:
      ################# Ljus ###################################################
      natural_light_outside:
        device_class: light
        friendly_name: Utomhus
        value_template: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float > states('input_number.utomhusbelysning_light_level') | float }}
      ### Utomhusbelysning
      utomhusbelysning_automation_control:
        friendly_name: Utomhusbelysning
        delay_off:
          minutes: 10
        value_template: >-
          {{ is_state('binary_sensor.natural_light_outside', 'off') }}
      #
      ### Ljusslingor
      utomhus_ljusslingor_light_level:
        friendly_name: Utomhusbelysning ljusslingor
        delay_off:
          minutes: 10
        value_template: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < 40 }}
      utomhusbelysning_ljusslingor_automation_control:
        friendly_name: Utomhusbelysning ljusslingor
        value_template: >-
          {{ is_state('binary_sensor.utomhus_ljusslingor_light_level', 'on')
            and is_state('input_boolean.sovdags', 'off') }}
#            or is_state('binary_sensor.presence_utomhus', 'on') ) }}
#
automation:
  ################ Tänd lampor ute när det är mörkt ############################
  - alias: Utomhusbelysning
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.entre_dorr
          - light.groventre_dorr
          - light.koksentre_dorr
          - light.snickarboa_entre
  #
  ### Ljusslingor
  - alias: ljusslingor
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_ljusslingor_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_ljusslingor_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_ljusslingor_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.entre_ljusslinga
          - light.koksentre_ljusslinga
