################# Circadian ##############################################
adaptive_lighting:
  - name: Utomhusbelysning
    lights:
    - light.groventre_dorr
    - light.koksentre_dorr
    prefer_rgb_color: false
    transition: 0
    initial_transition: 0
    interval: 90
    min_brightness: 20
    max_brightness: 90
    min_color_temp: 2200
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
#    sunrise_time: "08:00:00"  # override the sunrise time
#    sunrise_offset:
#    sunset_time:
#    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: true
#
  - name: Utomhusbelysning hue
    lights:
    - light.entre_dorr
    prefer_rgb_color: false
    transition: 30
    initial_transition: 1
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2200
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
#    sunrise_time: "08:00:00"  # override the sunrise time
#    sunrise_offset:
#    sunset_time:
#    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: false
#
binary_sensor:
  - platform: template
    sensors:
  ################# Ljus ###################################################
      natural_light_outside:
        device_class: light
        friendly_name: Utomhus
        value_template: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float > 200 }}
### Utomhusbelysning
      utomhusbelysning_automation_control:
        friendly_name: Utomhusbelysning
        delay_off:
          minutes: 10
        value_template: >-
          {{ is_state('binary_sensor.natural_light_outside', 'off') }}
#
automation:
################ Tänd lampor ute när det är mörkt ############################
- alias: Utomhusbelysning
  trigger:
  - platform: state
    entity_id: binary_sensor.utomhusbelysning_automation_control
  - platform: homeassistant
    event: start
  action:
  - service: >
      {% if is_state('binary_sensor.utomhusbelysning_automation_control', 'on') %}
      light.turn_on
      {% elif is_state('binary_sensor.utomhusbelysning_automation_control', 'off') %}
      light.turn_off
      {% endif %}
    entity_id:
    - light.entre_dorr
    - light.groventre_dorr
    - light.koksentre_dorr