################# Circadian ##############################################
adaptive_lighting:
  - name: Utomhusbelysning
    lights:
      - light.groventre_dorr
      - light.koksentre_dorr
    prefer_rgb_color: false
    transition: 0
    initial_transition: 0
    interval: 90
    min_brightness: 20
    max_brightness: 90
    min_color_temp: 2200
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: true
  #
  - name: Utomhusbelysning hue
    lights:
      - light.entre_dorr
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 20
    max_brightness: 100
    min_color_temp: 2100
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
    take_over_control: true
    detect_non_ha_changes: false
  #
  - name: Utomhusbelysning filament
    lights:
      - light.snickarboa_entre
      - light.stall_entre
      - light.carport_entre
      - light.kackorna_entre
      - light.stolpe_gang
      - light.stolpe_grind
      - light.light_4
    prefer_rgb_color: false
    transition: 30
    initial_transition: 5
    interval: 90
    min_brightness: 40
    max_brightness: 100
    min_color_temp: 2100
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2200
    take_over_control: true
    detect_non_ha_changes: false
    #
light:
  - platform: group
    name: Utomhusbelysning grupp
    unique_id: utomhusbelysning_grupp
    entities:
      - light.entre_dorr
      - light.groventre_dorr
      - light.koksentre_dorr
      - light.entre_ljusslinga
      - light.koksentre_ljusslinga
      - light.vaxthus_ljusslinga
      - light.snickarboa_entre
      - light.stall_entre
      - light.carport_entre
      - light.kackorna_entre
      - light.stall_entre
      - light.stolpe_gang
      - light.stolpe_grind
      - light.light_4
      - light.carport_belysning
#
input_number:
  utomhusbelysning_light_level:
    name: Ljusstyrka för utomhusbelysning
    min: 0
    max: 400
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
  # 40
  ljusslingor_light_level:
    name: Ljusstyrka för ljusslingor
    min: 0
    max: 400
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
template:
  - binary_sensor:
      #
      ### Närvaro
      - name: entre_presence
        unique_id: entre_presence
        device_class: motion
        delay_off:
          minutes: 5
        state: >
          {{ is_state('binary_sensor.entre_hue_outdoor_motion_sensor_motion', 'on')
            or is_state('binary_sensor.hall_dorrtrigger', 'on') }}
      #
      ################# Ljus ###################################################
      - name: utomhusbelysning_light_level
        unique_id: utomhusbelysning_light_level
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.utomhusbelysning_light_level') | float }}
      #
      ### Utomhusbelysning
      - name: utomhusbelysning_automation_control
        unique_id: utomhusbelysning_automation_control
        state: >
          {{ is_state('binary_sensor.utomhusbelysning_light_level', 'on') }}
      #
      ### Entré
      - name: entre_presence_automation_control
        unique_id: entre_presence_automation_control
        state: >
          {{ is_state('binary_sensor.utomhusbelysning_light_level', 'on')
            and is_state('binary_sensor.entre_presence', 'on') }}
      #
      ### Utomhusbelysning film
      - name: utomhusbelysning_film_automation_control
        unique_id: utomhusbelysning_film_automation_control
        state: >
          {{ is_state('binary_sensor.utomhusbelysning_light_level', 'on')
            and is_state('input_boolean.film_spelar', 'off') }}
      #
      ### Ljusslingor
      - name: utomhus_ljusslingor_light_level
        unique_id: utomhus_ljusslingor_light_level
        delay_off:
          minutes: 10
        state: >
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.ljusslingor_light_level') | float }}
      #
      - name: utomhusbelysning_ljusslingor_automation_control
        unique_id: utomhusbelysning_ljusslingor_automation_control
        state: >
          {{ is_state('binary_sensor.utomhus_ljusslingor_light_level', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
#
#
automation:
  ################ Tänd lampor ute när det är mörkt ############################
  - alias: Utomhusbelysning
    id: Utomhusbelysning
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.groventre_dorr
          - light.carport_entre
          - light.stolpe_gang
          - light.stolpe_grind
          - light.light_4
    #
    # Entré
  - alias: Entré belysning
    id: Entré belysning
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.entre_dorr
#
  - alias: Entré närvarobelysning
    id: Entré närvarobelysning
    trigger:
      - platform: state
        entity_id: binary_sensor.entre_presence_automation_control
      - platform: homeassistant
        event: start
    action:
      - choose:
          #
          - conditions:
              - condition: state
                state: 'on'
                entity_id: binary_sensor.entre_presence_automation_control
            sequence:
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_adapt_brightness_utomhusbelysning_hue
              - service: light.turn_on
                entity_id:
                    - light.entre_dorr
                data:
                  brightness_pct: 100
          #
          - conditions:
              - condition: state
                state: 'off'
                entity_id: binary_sensor.entre_presence_automation_control
            sequence:
#              - service: light.turn_off
#                entity_id:
#                    - light.entre_dorr
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_adapt_brightness_utomhusbelysning_hue
#
#
  - alias: Utomhusbelysning film
    id: Utomhusbelysning film
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_film_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_film_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_film_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.koksentre_dorr
          - light.snickarboa_entre
          - light.stall_entre
          - light.kackorna_entre
  #
  ### Ljusslingor
  - alias: Ljusslingor
    id: Ljusslingor
    trigger:
      - platform: state
        entity_id: binary_sensor.utomhusbelysning_ljusslingor_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.utomhusbelysning_ljusslingor_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.utomhusbelysning_ljusslingor_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.entre_ljusslinga
          - light.koksentre_ljusslinga
          - light.vaxthus_ljusslinga
