###################### Fjärrkontroll ###################################
#
automation:
- alias: Fjärrkontroll Film stopp
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:1"
      values:
        Command: "On"
  action:
  - service: media_player.media_stop
    entity_id: media_player.vardagsrum
#
- alias: Fjärrkontroll Film
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:2"
      values:
        Command: "On"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.film
#
- alias: Fjärrkontroll Film av
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:2"
      values:
        Command: "Off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.film
#
- alias: Fjärrkontroll Film paus
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:3"
      values:
        Command: "On"
  action:
  - service: media_player.media_pause
    entity_id: media_player.vardagsrum
  - service: media_player.media_pause
    entity_id: media_player.playstation_4
#
- alias: Fjärrkontroll Film play
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:3"
      values:
        Command: "Off"
  action:
  - service: media_player.media_play
    entity_id: media_player.vardagsrum
  - service: media_player.media_play
    entity_id: media_player.playstation_4
#
- alias: Fjärrkontroll Film lampor
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:4"
      values:
        Command: "On"
  action:
    service: automation.trigger
    entity_id: automation.film_play
#
- alias: Fjärrkontroll Film lampor off
  trigger:
  - platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "1656792:4"
      values:
        Command: "Off"
  action:
    service: automation.trigger
    entity_id: automation.film_pause