################# Circadian ##############################################
adaptive_lighting:
  #
  - name: Vardagsrum belysning filament
    lights:
      - light.vardagsrum_fonster_hangande
#      - light.vardagsrum_huslampa
      - light.vardagsrum_fonster_fotogen
      - light.vardagsrum_fonster_piano
      - light.vardagsrum_fonster_trappa
      - light.vardagsrum_fonster_ytterdorr
      - light.vardagsrum_fonster_vitrinskap
    prefer_rgb_color: false
    transition: 45
    initial_transition: 5
    interval: 90
    min_brightness: 1
    max_brightness: 45
    min_color_temp: 2100
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
    #sunrise_time: "07:00:00" # override the sunrise time
    #    sunrise_offset: -00:05:00
    #    sunset_time: '20:00'
    #    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: true
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
#
light:
  - platform: group
    name: Vardagsrum
    unique_id: vardagsrum
    entities:
      - light.vardagsrum_fonster_hangande
#      - light.vardagsrum_huslampa
      - light.vardagsrum_fonster_fotogen
      - light.vardagsrum_fonster_piano
      - light.vardagsrum_fonster_trappa
      - light.vardagsrum_tak
      - light.vardagsrum_fonster_ytterdorr
      - light.vardagsrum_fonster_vitrinskap
#
input_number:
  vardagsrum_light_level:
    name: Ljusstyrka vardagsrum för belysning
    min: 0
    max: 100
    step: 1
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
  vardagsrum_filament_light_level:
    name: Ljusstyrka vardagsrum för belysning filament
    min: 0
    max: 2000
    step: 10
    unit_of_measurement: lx
    icon: mdi:lightbulb-on
#
template:
    - binary_sensor:
      ### Light level
      - name: vardagsrum_lightlevel
        unique_id: vardagsrum_lightlevel
        device_class: light
        delay_on:
          minutes: 10
        state: >-
          {{ states('sensor.vardagsrum_hue_motion_sensor_light_level') | float > states('input_number.vardagsrum_light_level') | float }}
      ### Light level
      - name: vardagsrum_belysning_fonster_lightlevel
        unique_id: vardagsrum_belysning_fonster_lightlevel
#        device_class: light
        delay_off:
          minutes: 10
        state: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.fonsterbelysning_light_level') | float }}
      #
      - name: vardagsrum_belysning_filament_lightlevel
        unique_id: vardagsrum_belysning_filament_lightlevel
#        device_class: light
        delay_off:
          minutes: 10
        state: >-
          {{ states('sensor.entre_hue_outdoor_motion_sensor_light_level') | float < states('input_number.vardagsrum_filament_light_level') | float }}
      #
      # Belysning närvaro
      - name: vardagsrum_presence_light_automation_control
        unique_id: vardagsrum_presence_light_automation_control
        state: >-
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on') )
            and is_state('binary_sensor.vardagsrum_lightlevel', 'off') }}
      #
      ### Belysning fönster
      - name: vardagsrum_belysning_fonster_automation_control
        unique_id: vardagsrum_belysning_fonster_automation_control
        state: >-
          {{ is_state('binary_sensor.vardagsrum_belysning_fonster_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
      #
      ### Belysning filament
      - name: vardagsrum_belysning_filament_automation_control
        unique_id: vardagsrum_belysning_filament_automation_control
        state: >-
          {{ ( is_state('binary_sensor.vardagsrum_presence', 'on')
            or is_state('binary_sensor.kok_presence', 'on') )
            and is_state('binary_sensor.vardagsrum_belysning_filament_lightlevel', 'on')
            and is_state('input_boolean.film_spelar', 'off')
            and is_state('input_boolean.sovdags', 'off') }}
      ### Light level
      ### Närvaro
      - name: vardagsrum_presence
        unique_id: vardagsrum_presence
        device_class: motion
        delay_off:
          minutes: 20
        state: >-
          {{ is_state('binary_sensor.vardagsrum_hue_motion_sensor_motion', 'on') }}
      #
#
#
automation:
  #
  - alias: Vardagsrum belysning fönster
    trigger:
      - platform: state
        entity_id: binary_sensor.vardagsrum_belysning_fonster_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.vardagsrum_belysning_fonster_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.vardagsrum_belysning_fonster_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.vardagsrum_fonster_piano
          - light.vardagsrum_fonster_trappa
          - light.vardagsrum_fonster_ytterdorr
          - light.vardagsrum_fonster_vitrinskap
#
  - alias: Vardagsrum belysning filament
    trigger:
      - platform: state
        entity_id: binary_sensor.vardagsrum_belysning_filament_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.vardagsrum_belysning_filament_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.vardagsrum_belysning_filament_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
#          - light.vardagsrum_huslampa
          - light.vardagsrum_fonster_fotogen
          - light.vardagsrum_fonster_hangande
#
  - alias: Vardagsrum belysning tak
    trigger:
      - platform: state
        entity_id: binary_sensor.vardagsrum_presence_light_automation_control
      - platform: homeassistant
        event: start
    action:
      - service: >
          {% if is_state('binary_sensor.vardagsrum_presence_light_automation_control', 'on') %}
          light.turn_on
          {% elif is_state('binary_sensor.vardagsrum_presence_light_automation_control', 'off') %}
          light.turn_off
          {% endif %}
        entity_id:
          - light.vardagsrum_tak
          - light.vardagsrum_bord