# H채mtar data fr책n rest-api Viva
sensor:
      ### Marstrand
  - platform: rest
    resource: https://services.viva.sjofartsverket.se:8080/output/vivaoutputservice.svc/vivastation/69
    name: Marstrand vattentemp
    value_template: '{{ value_json["GetSingleStationResult"]["Samples"][1]["Value"] }}'
    unit_of_measurement: "째C"
      ### Torshamnen
#    - platform: rest
#      resource: https://services.viva.sjofartsverket.se:8080/output/vivaoutputservice.svc/vivastation/101
#      name: Torshamnen vattentemp
#      value_template: '{{ value_json["GetSingleStationResult"]["Samples"][3]["Value"] }}'
#      unit_of_measurement: "째C"
      ### Petroport
#    - platform: rest
#      resource: https://services.viva.sjofartsverket.se:8080/output/vivaoutputservice.svc/vivastation/143
#      name: Petroport medelvind
#      value_template: '{{ value_json["GetSingleStationResult"]["Samples"][1]["Value"] }}'
#      unit_of_measurement: "m/s"
#    - platform: rest
#      resource: https://services.viva.sjofartsverket.se:8080/output/vivaoutputservice.svc/vivastation/143
#      name: Petroport byvind
#      value_template: '{{ value_json["GetSingleStationResult"]["Samples"][0]["Value"] }}'
#      unit_of_measurement: "m/s"