################# Circadian ##############################################
adaptive_lighting:
  - name: Walk in closet
    lights:
    - light.walk_in_closet
    prefer_rgb_color: false
    transition: 1
    initial_transition: 0
    interval: 90
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2200
    max_color_temp: 4000
    sleep_brightness: 1
    sleep_color_temp: 2000
#    sunrise_time: "08:00:00"  # override the sunrise time
#    sunrise_offset:
#    sunset_time: "20:00:00"
#    sunset_offset: 1800  # in seconds or '00:15:00'
    # If another source calls light.turn_on while the lights are on and being adapted, disable Adaptive Lighting.
    take_over_control: true
    detect_non_ha_changes: false
    # Whether to keep adapting the lights (false) or to only adapt the lights as soon as they are turned on (true).
    only_once: false
    separate_turn_on_commands: true
#
binary_sensor:
  - platform: template
    sensors:
      ### Närvaro
      walk_in_closet_presence:
        device_class: motion
        friendly_name: Walk in closet
        delay_off:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.walk_in_closet_hue_motion_sensor_motion', 'on') }}
      ### Närvarostyrd belysning
      walk_in_closet_presence_light_automation_control:
        friendly_name: Walk in closet
        value_template: >-
          {{ is_state('binary_sensor.walk_in_closet_presence', 'on') }}
#
automation:
#
- alias: Walk in closet belysning
  trigger:
  - platform: state
    entity_id: binary_sensor.walk_in_closet_presence_light_automation_control
  - platform: homeassistant
    event: start
  action:
  - service: >
      {% if is_state('binary_sensor.walk_in_closet_presence_light_automation_control', 'on') %}
      light.turn_on
      {% elif is_state('binary_sensor.walk_in_closet_presence_light_automation_control', 'off') %}
      light.turn_off
      {% endif %}
    entity_id:
      - light.walk_in_closet