### Sensor ###
sensor:
  #
  - platform: statistics
    entity_id: sensor.netatmo_sannesholma_weather_station_pressure
    name: netatmo_sannesholma_weather_station_pressure_max
    state_characteristic: value_max
    sampling_size: 144
    max_age:
      minutes: 1440
    #
  - platform: statistics
    entity_id: sensor.netatmo_sannesholma_weather_station_pressure
    name: netatmo_sannesholma_weather_station_pressure_min
    state_characteristic: value_min
    sampling_size: 144
    max_age:
      minutes: 1440
#