### Sensor ###
sensor:
  #
  - platform: statistics
    entity_id: sensor.netatmo_sannesholma_weather_station_pressure
    name: netatmo_sannesholma_weather_station_pressure_max
    state_characteristic: value_max
    sampling_size: 144
    max_age:
      minutes: 1440
    #
  - platform: statistics
    entity_id: sensor.netatmo_sannesholma_weather_station_pressure
    name: netatmo_sannesholma_weather_station_pressure_min
    state_characteristic: value_min
    sampling_size: 144
    max_age:
      minutes: 1440
#  - platform: template
#    sensors:
#      netatmo_indoor_pressure_max:
#        unit_of_measurement: "mbar"
#        friendly_name: Pressure Max
#        value_template: "{{ state_attr('sensor.netatmo_sannesholma_weather_station_pressure_statistics', 'max_value') }}"
#      netatmo_indoor_pressure_min:
#        unit_of_measurement: "mbar"
#        friendly_name: Pressure Min
#        value_template: "{{ state_attr('sensor.netatmo_sannesholma_weather_station_pressure_statistics', 'min_value') }}"

### Trafikverket ###
#  - platform: trafikverket_weatherstation
#    name: Trafikverket Brokhult
#    api_key: !secret trafikverket_api_key
#    station: Brokhult
#    monitored_conditions:
#      - air_temp
#      - road_temp
#      - precipitation
#      - wind_direction
#      - wind_direction_text
#      - wind_speed
#      - wind_speed_max
#      - precipitation_amount
#      - precipitation_amountname

### SMHI Alert
  - platform: smhialert
    district: '017'
    language: 'sv'
### Vädervarningar
automation:
  - alias: 'SMHI Alert'
    trigger:
      platform: state
      entity_id: sensor.smhialert
      to: "Alert"
    action:
      - service: notify.pushbullet_lina
        data_template:
          title: "SMHI"
          message: '{{states.sensor.smhialert.attributes.notice}}'
      - service: notify.pushbullet
        data_template:
          title: 'SMHI'
          message: '{{states.sensor.smhialert.attributes.notice}}'