# =================================================================
# VINSTBERÄKNING FÖR SÅLD BATTERIENENERGI (EKONOMISK MODELL)
# =================================================================
# Logik för att beräkna intäkt från såld batterienergi och besparing
# från batteriets självförbrukning. Modellen antar: sälj sol först,
# dvs export täcks primärt av solel; resterande export antas komma
# från batteriet.
# -----------------------------------------------------------------

# =================================================================
# TEMPLATE-SENSORER
# =================================================================
template:
  - sensor:
      # Effekt såld från batteriet (EMHASS-modell: sälj sol först)
      - name: solar_battery_power_sold
        unique_id: solar_battery_power_sold
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: "{{ is_number(states('sensor.power_production_sannesholma_2181')) and is_number(states('sensor.solar_power_photovoltaics')) }}"
        state: >
          {% set total_export = states('sensor.power_production_sannesholma_2181') | float(0) %}
          {% set solar_prod_w = states('sensor.solar_power_photovoltaics') | float(0) %}
          {{ max(0, (total_export - solar_prod_w)) | round(0) }}

      # Batteriets självförbrukade effekt (inte såld)
      - name: solar_battery_power_self_usage
        unique_id: solar_battery_power_self_usage
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: "{{ is_number(states('sensor.solar_battery_discharging')) and is_number(states('sensor.solar_battery_power_sold')) }}"
        state: >
          {{ max(0, (states('sensor.solar_battery_discharging') | float(0) - states('sensor.solar_battery_power_sold') | float(0))) | round(0) }}

      # INTÄKT per timme (SEK) från såld batterienergi
      - name: solar_battery_sold_earnings_hour
        unique_id: solar_battery_sold_earnings_hour
        unit_of_measurement: "SEK"
        state_class: total_increasing
        availability: "{{ is_number(states('sensor.solar_battery_energy_sold_hour')) and is_number(states('sensor.elpris_produktion')) }}"
        state: >
          {{ (states('sensor.solar_battery_energy_sold_hour') | float(0)
              * max(0, states('sensor.elpris_produktion') | float(0))) | round(3) }}

      # BESPARING per timme (SEK) från batteriets självförbrukning
      - name: solar_battery_self_usage_savings_hour
        unique_id: solar_battery_self_usage_savings_hour
        unit_of_measurement: "SEK"
        state_class: total_increasing
        availability: "{{ is_number(states('sensor.solar_battery_energy_self_usage_hour')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: >
          {{ (states('sensor.solar_battery_energy_self_usage_hour') | float(0)
              * max(0, states('sensor.elpris_totalt_sek') | float(0))) | round(3) }}

# =================================================================
# INTEGRATION-SENSORER (W → kWh)
# =================================================================
sensor:
  - platform: integration
    source: sensor.solar_battery_power_sold
    name: solar_battery_energy_sold
    unique_id: solar_battery_energy_sold
    unit_prefix: k
    method: left
    round: 3

  - platform: integration
    source: sensor.solar_battery_power_self_usage
    name: solar_battery_energy_self_usage
    unique_id: solar_battery_energy_self_usage
    unit_prefix: k
    method: left
    round: 3

# =================================================================
# UTILITY METERS
# =================================================================
utility_meter:
  # Såld energi från batteriet (kWh)
  solar_battery_energy_sold_hour:
    unique_id: solar_battery_energy_sold_hour
    source: sensor.solar_battery_energy_sold
    periodically_resetting: false
    cycle: hourly
  solar_battery_energy_sold_month:
    unique_id: solar_battery_energy_sold_month
    source: sensor.solar_battery_energy_sold
    periodically_resetting: false
    cycle: monthly

  # Självförbrukad batterienergi (kWh)
  solar_battery_energy_self_usage_hour:
    unique_id: solar_battery_energy_self_usage_hour
    source: sensor.solar_battery_energy_self_usage
    periodically_resetting: false
    cycle: hourly
  solar_battery_energy_self_usage_month:
    unique_id: solar_battery_energy_self_usage_month
    source: sensor.solar_battery_energy_self_usage
    periodically_resetting: false
    cycle: monthly

  # Ekonomi (SEK) – summerar timvärden som aldrig är negativa
  solar_battery_sold_earnings_month:
    unique_id: solar_battery_sold_earnings_month
    source: sensor.solar_battery_sold_earnings_hour
    cycle: monthly

  solar_battery_self_usage_savings_month:
    unique_id: solar_battery_self_usage_savings_month
    source: sensor.solar_battery_self_usage_savings_hour
    cycle: monthly