# =================================================================
# VINSTBERÄKNING FÖR SÅLD BATTERIENENERGI (EKONOMISK MODELL)
# =================================================================
# All logik för att beräkna den faktiska vinsten som genereras
# genom att sälja lagrad el från batteriet till elnätet, baserat
# på en ekonomisk modell som prioriterar försäljning av solenergi.
# -----------------------------------------------------------------

# =================================================================
# TEMPLATE-SENSORER
# =================================================================
# Dessa sensorer utför de grundläggande beräkningarna.
# -----------------------------------------------------------------
template:
  - sensor:
      # --- Effekt såld från batteriet (Ekonomisk modell) ---
      # Denna sensor beräknar hur mycket effekt som säljs från batteriet
      # enligt EMHASS ekonomiska modell: sälj solenergi först.
      - name: solar_battery_power_sold
        unique_id: solar_battery_power_sold
        unit_of_measurement: W
        state_class: measurement
        device_class: power
        state: >
          {% set total_export = states('sensor.power_production_sannesholma_2181') | float(0) %}
          {% set solar_production = states('sensor.solar_power_photovoltaics') | float(0) %}
          {{ max(0, total_export - solar_production) | round(0) }}

      # --- Självförbrukad effekt från batteriet (Ekonomisk modell) ---
      # Beräknar hur mycket av batteriets urladdning som, enligt den
      # ekonomiska modellen, används för att täcka husets behov.
      - name: solar_battery_power_self_usage
        unique_id: solar_battery_power_self_usage
        unit_of_measurement: W
        state_class: measurement
        device_class: power
        state: >
          {{ (states('sensor.solar_battery_discharging') | float(0) - states('sensor.solar_battery_power_sold') | float(0)) | round(0) }}

      # --- Förtjänst från såld batterienergi (per timme) ---
      # Beräknar det monetära värdet av den el som sålts från batteriet
      # under den innevarande timmen.
      - name: solar_battery_sold_earnings_hour
        unique_id: solar_battery_sold_earnings_hour
        unit_of_measurement: "SEK"
        state_class: total
        availability: "{{ is_number(states('sensor.solar_battery_energy_sold_hour')) and is_number(states('sensor.elpris_produktion')) }}"
        state: "{{ ( states('sensor.solar_battery_energy_sold_hour') | float('naan') * states('sensor.elpris_produktion') | float('naan') ) | round(3) }}"

      # --- Besparing från självförbrukad batterienergi (per timme) ---
      # Beräknar det monetära värdet (undviken kostnad) av den el från
      # batteriet som använts i huset under den innevarande timmen.
      - name: solar_battery_self_usage_savings_hour
        unique_id: solar_battery_self_usage_savings_hour
        unit_of_measurement: "SEK"
        state_class: total
        availability: "{{ is_number(states('sensor.solar_battery_energy_self_usage_hour')) and is_number(states('sensor.elpris_totalt_sek')) }}"
        state: "{{ ( states('sensor.solar_battery_energy_self_usage_hour') | float('naan') * states('sensor.elpris_totalt_sek') | float('naan') ) | round(3) }}"

# =================================================================
# INTEGRATION-SENSORER
# =================================================================
# Dessa sensorer konverterar effekt (W) till energi (kWh) över tid.
# -----------------------------------------------------------------
sensor:
  - platform: integration
    source: sensor.solar_battery_power_sold
    name: solar_battery_energy_sold
    unique_id: solar_battery_energy_sold
    unit_prefix: k
    method: left
  - platform: integration
    source: sensor.solar_battery_power_self_usage
    name: solar_battery_energy_self_usage
    unique_id: solar_battery_energy_self_usage
    unit_prefix: k
    method: left

# =================================================================
# UTILITY METERS
# =================================================================
# Dessa entiteter spårar den sålda och självförbrukade batterienergin
# samt den relaterade förtjänsten och besparingen över tid.
# -----------------------------------------------------------------
utility_meter:
  # --- Såld energi från batteriet ---
  solar_battery_energy_sold_hour:
    unique_id: solar_battery_energy_sold_hour
    source: sensor.solar_battery_energy_sold
    periodically_resetting: false
    cycle: hourly
  solar_battery_energy_sold_month:
    unique_id: solar_battery_energy_sold_month
    source: sensor.solar_battery_energy_sold
    periodically_resetting: false
    cycle: monthly

  # --- Självförbrukad energi från batteriet ---
  solar_battery_energy_self_usage_hour:
    unique_id: solar_battery_energy_self_usage_hour
    source: sensor.solar_battery_energy_self_usage
    periodically_resetting: false
    cycle: hourly
  solar_battery_energy_self_usage_month:
    unique_id: solar_battery_energy_self_usage_month
    source: sensor.solar_battery_energy_self_usage
    periodically_resetting: false
    cycle: monthly

  # --- Förtjänst från såld batterienergi ---
  solar_battery_sold_earnings_month:
    unique_id: solar_battery_sold_earnings_month
    source: sensor.solar_battery_sold_earnings_hour
    cycle: monthly
  
  # --- Besparing från självförbrukad batterienergi ---
  solar_battery_self_usage_savings_month:
    unique_id: solar_battery_self_usage_savings_month
    source: sensor.solar_battery_self_usage_savings_hour
    cycle: monthly