# =================================================================
# FÖRTJÄNSTBERÄKNING FÖR SÅLD SOLENERGI
# =================================================================
# Logik för att korrekt beräkna vinsten från såld solel.
# Separat från batteri – använder total export minus batteriexport.
# Räknar energi (kWh), intäkt (SEK/h), och summerar dag/månad.
# -----------------------------------------------------------------

# =================================================================
# TEMPLATE-SENSORER
# =================================================================
template:
  - sensor:
      # --- Effekt såld från solen (Realtid, W) ---
      - name: solar_power_sold_from_sun
        unique_id: solar_power_sold_from_sun
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.power_production_sannesholma_2181')
            and has_value('sensor.solar_battery_power_sold') }}
        state: >
          {% set total_export  = states('sensor.power_production_sannesholma_2181') | float(0) %}
          {% set battery_export = states('sensor.solar_battery_power_sold') | float(0) %}
          {{ max(0, total_export - battery_export) | round(0) }}

      # --- Intäkt per timme (SEK/h) från såld solel ---
      - name: solar_sold_earnings_hour
        unique_id: solar_sold_earnings_hour
        unit_of_measurement: "SEK"
        state_class: total_increasing
        availability: >
          {{ has_value('sensor.solar_energy_sold_from_sun_hour')
            and has_value('sensor.elpris_produktion') }}
        state: >
          {{ (
            states('sensor.solar_energy_sold_from_sun_hour') | float(0)
            * max(0, states('sensor.elpris_produktion') | float(0))
          ) | round(3) }}

# =================================================================
# INTEGRATION-SENSORER (W → kWh)
# =================================================================
sensor:
  - platform: integration
    source: sensor.solar_power_sold_from_sun
    name: solar_energy_sold_from_sun
    unique_id: solar_energy_sold_from_sun
    unit_prefix: k
    method: left

# =================================================================
# UTILITY METERS
# =================================================================
utility_meter:
  # Energi såld från solen (kWh)
  solar_energy_sold_from_sun_hour:
    unique_id: solar_energy_sold_from_sun_hour
    source: sensor.solar_energy_sold_from_sun
    periodically_resetting: false
    cycle: hourly
  solar_energy_sold_from_sun_day:
    unique_id: solar_energy_sold_from_sun_day
    source: sensor.solar_energy_sold_from_sun
    periodically_resetting: false
    cycle: daily

  # Intäkt från såld solel (SEK)
  solar_sold_earnings_day:
    unique_id: solar_sold_earnings_day
    source: sensor.solar_sold_earnings_hour
    cycle: daily
  solar_sold_earnings_month:
    unique_id: solar_sold_earnings_month
    source: sensor.solar_sold_earnings_hour
    cycle: monthly