# =================================================================
# LOGIK FÖR FYSISKA KNAPPAR
# =================================================================
# All logik för att hantera tryck på fysiska knappar i gästrummet.
# -----------------------------------------------------------------

# --- Automation för knappen vid sängen ---
automation:
  - alias: Gästrum knapp vid säng
    id: Gästrum knapp vid säng
    trigger:
      - trigger: event
        event_type: deconz_event
        event_data:
          id: sovrum_knapp # OBS: Verkar använda samma knapp-ID som sovrummet?
          event: 1002
    actions:
      - action: input_boolean.toggle
        target:
          entity_id: input_boolean.sovdags_gastrum